package com.dy_web_api.sdk.message.protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3

public final class ChatMessage {
    private ChatMessage() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                ChatMessage.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry)
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry)
    {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Header_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Header_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PushFrame_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_PushFrame_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ResponseHeader_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ResponseHeader_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Response_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Response_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ResponseBody_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ResponseBody_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_NewMessageNotify_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_NewMessageNotify_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Entity_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Entity_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MessageBody_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_MessageBody_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor()
    {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021chatMessage.proto\"$\n\006Header\022\013\n\003key\030\001 \001" +
                        "(\t\022\r\n\005value\030\002 \001(\t\"\355\001\n\tPushFrame\022\r\n\005seqID" +
                        "\030\001 \001(\004\022\r\n\005logID\030\002 \001(\004\022\017\n\007service\030\003 \001(\005\022\016" +
                        "\n\006method\030\004 \001(\005\022\030\n\007headers\030\005 \003(\0132\007.Header" +
                        "\022\027\n\017payloadEncoding\030\006 \001(\t\022\023\n\013payloadType" +
                        "\030\007 \001(\t\022\017\n\007payload\030\010 \001(\014\022\020\n\010lodIdNew\030\t \001(" +
                        "\t\022\024\n\014serverTiming\030\n \001(\t\022\r\n\005msgID\030\013 \001(\t\022\021" +
                        "\n\tframeType\030\014 \001(\005\",\n\016ResponseHeader\022\013\n\003k" +
                        "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\311\001\n\010Response\022\013\n\003" +
                        "cmd\030\001 \001(\005\022\022\n\nsequenceId\030\002 \001(\003\022\022\n\nstatusC" +
                        "ode\030\003 \001(\005\022\021\n\terrorDesc\030\004 \001(\t\022\021\n\tinboxTyp" +
                        "e\030\005 \001(\005\022\033\n\004body\030\006 \001(\0132\r.ResponseBody\022\r\n\005" +
                        "logId\030\007 \001(\t\022\026\n\016startTimestamp\030\t \001(\003\022\036\n\026s" +
                        "erverExecutionEndTime\030\n \001(\003\"?\n\014ResponseB" +
                        "ody\022/\n\023hasNewMessageNotify\030\364\003 \001(\0132\021.NewM" +
                        "essageNotify\"\317\002\n\020NewMessageNotify\022\026\n\016con" +
                        "versationId\030\002 \001(\t\022\030\n\020conversationType\030\003 " +
                        "\001(\005\022\022\n\nnotifyType\030\004 \001(\005\022\035\n\007message\030\005 \001(\013" +
                        "2\014.MessageBody\022\026\n\016previousCursor\030\006 \001(\003\022\022" +
                        "\n\nnextCursor\030\007 \001(\003\022\033\n\023indexInConversatio" +
                        "n\030\010 \001(\003\022\036\n\026indexInConversation_v2\030\t \001(\003\022" +
                        "\033\n\023conversationVersion\030\n \001(\003\022#\n\033previous" +
                        "ConversationVersion\030\013 \001(\003\022\027\n\017cmdMessageI" +
                        "ndex\030\014 \001(\003\022\022\n\nbadgeCount\030\r \001(\005\"$\n\006Entity" +
                        "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\314\002\n\013Message" +
                        "Body\022\026\n\016conversationId\030\001 \001(\t\022\030\n\020conversa" +
                        "tionType\030\002 \001(\005\022\027\n\017serverMessageId\030\003 \001(\003\022" +
                        "\033\n\023indexInConversation\030\004 \001(\003\022\033\n\023conversa" +
                        "tionShortId\030\005 \001(\003\022\023\n\013messageType\030\006 \001(\005\022\016" +
                        "\n\006sender\030\007 \001(\003\022\017\n\007content\030\010 \001(\t\022\022\n\ncreat" +
                        "eTime\030\n \001(\003\022\017\n\007version\030\013 \001(\003\022\016\n\006status\030\014" +
                        " \001(\005\022\033\n\023orderInConversation\030\r \001(\003\022\021\n\tsec" +
                        "Sender\030\016 \001(\t\022\035\n\025indexInConversationV2\030\021 " +
                        "\001(\003B\002P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Header_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Header_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Header_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_PushFrame_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_PushFrame_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_PushFrame_descriptor,
                new java.lang.String[]{"SeqID", "LogID", "Service", "Method", "Headers", "PayloadEncoding", "PayloadType", "Payload", "LodIdNew", "ServerTiming", "MsgID", "FrameType",});
        internal_static_ResponseHeader_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_ResponseHeader_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ResponseHeader_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_Response_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_Response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Response_descriptor,
                new java.lang.String[]{"Cmd", "SequenceId", "StatusCode", "ErrorDesc", "InboxType", "Body", "LogId", "StartTimestamp", "ServerExecutionEndTime",});
        internal_static_ResponseBody_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_ResponseBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ResponseBody_descriptor,
                new java.lang.String[]{"HasNewMessageNotify",});
        internal_static_NewMessageNotify_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_NewMessageNotify_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_NewMessageNotify_descriptor,
                new java.lang.String[]{"ConversationId", "ConversationType", "NotifyType", "Message", "PreviousCursor", "NextCursor", "IndexInConversation", "IndexInConversationV2", "ConversationVersion", "PreviousConversationVersion", "CmdMessageIndex", "BadgeCount",});
        internal_static_Entity_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_Entity_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Entity_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_MessageBody_descriptor =
                getDescriptor().getMessageTypes().get(7);
        internal_static_MessageBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_MessageBody_descriptor,
                new java.lang.String[]{"ConversationId", "ConversationType", "ServerMessageId", "IndexInConversation", "ConversationShortId", "MessageType", "Sender", "Content", "CreateTime", "Version", "Status", "OrderInConversation", "SecSender", "IndexInConversationV2",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
