// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;


public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Header)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     *
     * @return The key.
     */
    java.lang.String getKey();

    /**
     * <code>string key = 1;</code>
     *
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
    getKeyBytes();

    /**
     * <code>string value = 2;</code>
     *
     * @return The value.
     */
    java.lang.String getValue();

    /**
     * <code>string value = 2;</code>
     *
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
    getValueBytes();
}
