// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

public interface MessageBodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MessageBody)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string conversationId = 1;</code>
     *
     * @return The conversationId.
     */
    java.lang.String getConversationId();

    /**
     * <code>string conversationId = 1;</code>
     *
     * @return The bytes for conversationId.
     */
    com.google.protobuf.ByteString
    getConversationIdBytes();

    /**
     * <code>int32 conversationType = 2;</code>
     *
     * @return The conversationType.
     */
    int getConversationType();

    /**
     * <code>int64 serverMessageId = 3;</code>
     *
     * @return The serverMessageId.
     */
    long getServerMessageId();

    /**
     * <code>int64 indexInConversation = 4;</code>
     *
     * @return The indexInConversation.
     */
    long getIndexInConversation();

    /**
     * <code>int64 conversationShortId = 5;</code>
     *
     * @return The conversationShortId.
     */
    long getConversationShortId();

    /**
     * <code>int32 messageType = 6;</code>
     *
     * @return The messageType.
     */
    int getMessageType();

    /**
     * <code>int64 sender = 7;</code>
     *
     * @return The sender.
     */
    long getSender();

    /**
     * <code>string content = 8;</code>
     *
     * @return The content.
     */
    java.lang.String getContent();

    /**
     * <code>string content = 8;</code>
     *
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
    getContentBytes();

    /**
     * <pre>
     * repeated Entity ext = 9;
     * </pre>
     *
     * <code>int64 createTime = 10;</code>
     *
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>int64 version = 11;</code>
     *
     * @return The version.
     */
    long getVersion();

    /**
     * <code>int32 status = 12;</code>
     *
     * @return The status.
     */
    int getStatus();

    /**
     * <code>int64 orderInConversation = 13;</code>
     *
     * @return The orderInConversation.
     */
    long getOrderInConversation();

    /**
     * <code>string secSender = 14;</code>
     *
     * @return The secSender.
     */
    java.lang.String getSecSender();

    /**
     * <code>string secSender = 14;</code>
     *
     * @return The bytes for secSender.
     */
    com.google.protobuf.ByteString
    getSecSenderBytes();

    /**
     * <code>int64 indexInConversationV2 = 17;</code>
     *
     * @return The indexInConversationV2.
     */
    long getIndexInConversationV2();
}
