// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

/**
 * Protobuf type {@code MessageBody}
 */
public final class MessageBody extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:MessageBody)
        MessageBodyOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                MessageBody.class.getName());
    }

    // Use MessageBody.newBuilder() to construct.
    private MessageBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private MessageBody() {
        conversationId_ = "";
        content_ = "";
        secSender_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor()
    {
        return ChatMessage.internal_static_MessageBody_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable()
    {
        return ChatMessage.internal_static_MessageBody_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        MessageBody.class, Builder.class);
    }

    public static final int CONVERSATIONID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object conversationId_ = "";

    /**
     * <code>string conversationId = 1;</code>
     *
     * @return The conversationId.
     */
    @Override
    public String getConversationId() {
        Object ref = conversationId_;
        if(ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            conversationId_ = s;
            return s;
        }
    }

    /**
     * <code>string conversationId = 1;</code>
     *
     * @return The bytes for conversationId.
     */
    @Override
    public com.google.protobuf.ByteString
    getConversationIdBytes()
    {
        Object ref = conversationId_;
        if(ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            conversationId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CONVERSATIONTYPE_FIELD_NUMBER = 2;
    private int conversationType_ = 0;

    /**
     * <code>int32 conversationType = 2;</code>
     *
     * @return The conversationType.
     */
    @Override
    public int getConversationType() {
        return conversationType_;
    }

    public static final int SERVERMESSAGEID_FIELD_NUMBER = 3;
    private long serverMessageId_ = 0L;

    /**
     * <code>int64 serverMessageId = 3;</code>
     *
     * @return The serverMessageId.
     */
    @Override
    public long getServerMessageId() {
        return serverMessageId_;
    }

    public static final int INDEXINCONVERSATION_FIELD_NUMBER = 4;
    private long indexInConversation_ = 0L;

    /**
     * <code>int64 indexInConversation = 4;</code>
     *
     * @return The indexInConversation.
     */
    @Override
    public long getIndexInConversation() {
        return indexInConversation_;
    }

    public static final int CONVERSATIONSHORTID_FIELD_NUMBER = 5;
    private long conversationShortId_ = 0L;

    /**
     * <code>int64 conversationShortId = 5;</code>
     *
     * @return The conversationShortId.
     */
    @Override
    public long getConversationShortId() {
        return conversationShortId_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 6;
    private int messageType_ = 0;

    /**
     * <code>int32 messageType = 6;</code>
     *
     * @return The messageType.
     */
    @Override
    public int getMessageType() {
        return messageType_;
    }

    public static final int SENDER_FIELD_NUMBER = 7;
    private long sender_ = 0L;

    /**
     * <code>int64 sender = 7;</code>
     *
     * @return The sender.
     */
    @Override
    public long getSender() {
        return sender_;
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";

    /**
     * <code>string content = 8;</code>
     *
     * @return The content.
     */
    @Override
    public String getContent() {
        Object ref = content_;
        if(ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            content_ = s;
            return s;
        }
    }

    /**
     * <code>string content = 8;</code>
     *
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
    getContentBytes()
    {
        Object ref = content_;
        if(ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            content_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CREATETIME_FIELD_NUMBER = 10;
    private long createTime_ = 0L;

    /**
     * <pre>
     * repeated Entity ext = 9;
     * </pre>
     *
     * <code>int64 createTime = 10;</code>
     *
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
        return createTime_;
    }

    public static final int VERSION_FIELD_NUMBER = 11;
    private long version_ = 0L;

    /**
     * <code>int64 version = 11;</code>
     *
     * @return The version.
     */
    @Override
    public long getVersion() {
        return version_;
    }

    public static final int STATUS_FIELD_NUMBER = 12;
    private int status_ = 0;

    /**
     * <code>int32 status = 12;</code>
     *
     * @return The status.
     */
    @Override
    public int getStatus() {
        return status_;
    }

    public static final int ORDERINCONVERSATION_FIELD_NUMBER = 13;
    private long orderInConversation_ = 0L;

    /**
     * <code>int64 orderInConversation = 13;</code>
     *
     * @return The orderInConversation.
     */
    @Override
    public long getOrderInConversation() {
        return orderInConversation_;
    }

    public static final int SECSENDER_FIELD_NUMBER = 14;
    @SuppressWarnings("serial")
    private volatile Object secSender_ = "";

    /**
     * <code>string secSender = 14;</code>
     *
     * @return The secSender.
     */
    @Override
    public String getSecSender() {
        Object ref = secSender_;
        if(ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            secSender_ = s;
            return s;
        }
    }

    /**
     * <code>string secSender = 14;</code>
     *
     * @return The bytes for secSender.
     */
    @Override
    public com.google.protobuf.ByteString
    getSecSenderBytes()
    {
        Object ref = secSender_;
        if(ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            secSender_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int INDEXINCONVERSATIONV2_FIELD_NUMBER = 17;
    private long indexInConversationV2_ = 0L;

    /**
     * <code>int64 indexInConversationV2 = 17;</code>
     *
     * @return The indexInConversationV2.
     */
    @Override
    public long getIndexInConversationV2() {
        return indexInConversationV2_;
    }

    private byte memoizedIsInitialized = - 1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if(isInitialized == 1) return true;
        if(isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException
    {
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(conversationId_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, conversationId_);
        }
        if(conversationType_ != 0) {
            output.writeInt32(2, conversationType_);
        }
        if(serverMessageId_ != 0L) {
            output.writeInt64(3, serverMessageId_);
        }
        if(indexInConversation_ != 0L) {
            output.writeInt64(4, indexInConversation_);
        }
        if(conversationShortId_ != 0L) {
            output.writeInt64(5, conversationShortId_);
        }
        if(messageType_ != 0) {
            output.writeInt32(6, messageType_);
        }
        if(sender_ != 0L) {
            output.writeInt64(7, sender_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 8, content_);
        }
        if(createTime_ != 0L) {
            output.writeInt64(10, createTime_);
        }
        if(version_ != 0L) {
            output.writeInt64(11, version_);
        }
        if(status_ != 0) {
            output.writeInt32(12, status_);
        }
        if(orderInConversation_ != 0L) {
            output.writeInt64(13, orderInConversation_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(secSender_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 14, secSender_);
        }
        if(indexInConversationV2_ != 0L) {
            output.writeInt64(17, indexInConversationV2_);
        }
        getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if(size != - 1) return size;

        size = 0;
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(conversationId_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, conversationId_);
        }
        if(conversationType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, conversationType_);
        }
        if(serverMessageId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(3, serverMessageId_);
        }
        if(indexInConversation_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(4, indexInConversation_);
        }
        if(conversationShortId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(5, conversationShortId_);
        }
        if(messageType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(6, messageType_);
        }
        if(sender_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(7, sender_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(8, content_);
        }
        if(createTime_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(10, createTime_);
        }
        if(version_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(11, version_);
        }
        if(status_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(12, status_);
        }
        if(orderInConversation_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(13, orderInConversation_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(secSender_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(14, secSender_);
        }
        if(indexInConversationV2_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(17, indexInConversationV2_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if(obj == this) {
            return true;
        }
        if(! (obj instanceof MessageBody)) {
            return super.equals(obj);
        }
        MessageBody other = (MessageBody) obj;

        if(! getConversationId()
                .equals(other.getConversationId())) return false;
        if(getConversationType()
                != other.getConversationType()) return false;
        if(getServerMessageId()
                != other.getServerMessageId()) return false;
        if(getIndexInConversation()
                != other.getIndexInConversation()) return false;
        if(getConversationShortId()
                != other.getConversationShortId()) return false;
        if(getMessageType()
                != other.getMessageType()) return false;
        if(getSender()
                != other.getSender()) return false;
        if(! getContent()
                .equals(other.getContent())) return false;
        if(getCreateTime()
                != other.getCreateTime()) return false;
        if(getVersion()
                != other.getVersion()) return false;
        if(getStatus()
                != other.getStatus()) return false;
        if(getOrderInConversation()
                != other.getOrderInConversation()) return false;
        if(! getSecSender()
                .equals(other.getSecSender())) return false;
        if(getIndexInConversationV2()
                != other.getIndexInConversationV2()) return false;
        if(! getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if(memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CONVERSATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getConversationId().hashCode();
        hash = (37 * hash) + CONVERSATIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getConversationType();
        hash = (37 * hash) + SERVERMESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getServerMessageId());
        hash = (37 * hash) + INDEXINCONVERSATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getIndexInConversation());
        hash = (37 * hash) + CONVERSATIONSHORTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getConversationShortId());
        hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageType();
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getSender());
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getCreateTime());
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getVersion());
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
        hash = (37 * hash) + ORDERINCONVERSATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getOrderInConversation());
        hash = (37 * hash) + SECSENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSecSender().hashCode();
        hash = (37 * hash) + INDEXINCONVERSATIONV2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getIndexInConversationV2());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static MessageBody parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static MessageBody parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MessageBody parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static MessageBody parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MessageBody parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static MessageBody parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MessageBody parseFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static MessageBody parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessageBody parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static MessageBody parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessageBody parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static MessageBody parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(MessageBody prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent)
    {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code MessageBody}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:MessageBody)
            MessageBodyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatMessage.internal_static_MessageBody_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatMessage.internal_static_MessageBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MessageBody.class, Builder.class);
        }

        // Construct using MessageBody.newBuilder()
        private Builder() {

        }

        private Builder(
                BuilderParent parent)
        {
            super(parent);

        }

        @Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            conversationId_ = "";
            conversationType_ = 0;
            serverMessageId_ = 0L;
            indexInConversation_ = 0L;
            conversationShortId_ = 0L;
            messageType_ = 0;
            sender_ = 0L;
            content_ = "";
            createTime_ = 0L;
            version_ = 0L;
            status_ = 0;
            orderInConversation_ = 0L;
            secSender_ = "";
            indexInConversationV2_ = 0L;
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType()
        {
            return ChatMessage.internal_static_MessageBody_descriptor;
        }

        @Override
        public MessageBody getDefaultInstanceForType() {
            return MessageBody.getDefaultInstance();
        }

        @Override
        public MessageBody build() {
            MessageBody result = buildPartial();
            if(! result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public MessageBody buildPartial() {
            MessageBody result = new MessageBody(this);
            if(bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(MessageBody result) {
            int from_bitField0_ = bitField0_;
            if(((from_bitField0_ & 0x00000001) != 0)) {
                result.conversationId_ = conversationId_;
            }
            if(((from_bitField0_ & 0x00000002) != 0)) {
                result.conversationType_ = conversationType_;
            }
            if(((from_bitField0_ & 0x00000004) != 0)) {
                result.serverMessageId_ = serverMessageId_;
            }
            if(((from_bitField0_ & 0x00000008) != 0)) {
                result.indexInConversation_ = indexInConversation_;
            }
            if(((from_bitField0_ & 0x00000010) != 0)) {
                result.conversationShortId_ = conversationShortId_;
            }
            if(((from_bitField0_ & 0x00000020) != 0)) {
                result.messageType_ = messageType_;
            }
            if(((from_bitField0_ & 0x00000040) != 0)) {
                result.sender_ = sender_;
            }
            if(((from_bitField0_ & 0x00000080) != 0)) {
                result.content_ = content_;
            }
            if(((from_bitField0_ & 0x00000100) != 0)) {
                result.createTime_ = createTime_;
            }
            if(((from_bitField0_ & 0x00000200) != 0)) {
                result.version_ = version_;
            }
            if(((from_bitField0_ & 0x00000400) != 0)) {
                result.status_ = status_;
            }
            if(((from_bitField0_ & 0x00000800) != 0)) {
                result.orderInConversation_ = orderInConversation_;
            }
            if(((from_bitField0_ & 0x00001000) != 0)) {
                result.secSender_ = secSender_;
            }
            if(((from_bitField0_ & 0x00002000) != 0)) {
                result.indexInConversationV2_ = indexInConversationV2_;
            }
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if(other instanceof MessageBody) {
                return mergeFrom((MessageBody) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(MessageBody other) {
            if(other == MessageBody.getDefaultInstance()) return this;
            if(! other.getConversationId().isEmpty()) {
                conversationId_ = other.conversationId_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if(other.getConversationType() != 0) {
                setConversationType(other.getConversationType());
            }
            if(other.getServerMessageId() != 0L) {
                setServerMessageId(other.getServerMessageId());
            }
            if(other.getIndexInConversation() != 0L) {
                setIndexInConversation(other.getIndexInConversation());
            }
            if(other.getConversationShortId() != 0L) {
                setConversationShortId(other.getConversationShortId());
            }
            if(other.getMessageType() != 0) {
                setMessageType(other.getMessageType());
            }
            if(other.getSender() != 0L) {
                setSender(other.getSender());
            }
            if(! other.getContent().isEmpty()) {
                content_ = other.content_;
                bitField0_ |= 0x00000080;
                onChanged();
            }
            if(other.getCreateTime() != 0L) {
                setCreateTime(other.getCreateTime());
            }
            if(other.getVersion() != 0L) {
                setVersion(other.getVersion());
            }
            if(other.getStatus() != 0) {
                setStatus(other.getStatus());
            }
            if(other.getOrderInConversation() != 0L) {
                setOrderInConversation(other.getOrderInConversation());
            }
            if(! other.getSecSender().isEmpty()) {
                secSender_ = other.secSender_;
                bitField0_ |= 0x00001000;
                onChanged();
            }
            if(other.getIndexInConversationV2() != 0L) {
                setIndexInConversationV2(other.getIndexInConversationV2());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            if(extensionRegistry == null) {
                throw new NullPointerException();
            }
            try {
                boolean done = false;
                while(! done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            conversationId_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 16: {
                            conversationType_ = input.readInt32();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        case 24: {
                            serverMessageId_ = input.readInt64();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 32: {
                            indexInConversation_ = input.readInt64();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 32
                        case 40: {
                            conversationShortId_ = input.readInt64();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 40
                        case 48: {
                            messageType_ = input.readInt32();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 48
                        case 56: {
                            sender_ = input.readInt64();
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 56
                        case 66: {
                            content_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000080;
                            break;
                        } // case 66
                        case 80: {
                            createTime_ = input.readInt64();
                            bitField0_ |= 0x00000100;
                            break;
                        } // case 80
                        case 88: {
                            version_ = input.readInt64();
                            bitField0_ |= 0x00000200;
                            break;
                        } // case 88
                        case 96: {
                            status_ = input.readInt32();
                            bitField0_ |= 0x00000400;
                            break;
                        } // case 96
                        case 104: {
                            orderInConversation_ = input.readInt64();
                            bitField0_ |= 0x00000800;
                            break;
                        } // case 104
                        case 114: {
                            secSender_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00001000;
                            break;
                        } // case 114
                        case 136: {
                            indexInConversationV2_ = input.readInt64();
                            bitField0_ |= 0x00002000;
                            break;
                        } // case 136
                        default: {
                            if(! super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private Object conversationId_ = "";

        /**
         * <code>string conversationId = 1;</code>
         *
         * @return The conversationId.
         */
        public String getConversationId() {
            Object ref = conversationId_;
            if(! (ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                conversationId_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string conversationId = 1;</code>
         *
         * @return The bytes for conversationId.
         */
        public com.google.protobuf.ByteString
        getConversationIdBytes()
        {
            Object ref = conversationId_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                conversationId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string conversationId = 1;</code>
         *
         * @param value The conversationId to set.
         * @return This builder for chaining.
         */
        public Builder setConversationId(
                String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            conversationId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string conversationId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConversationId() {
            conversationId_ = getDefaultInstance().getConversationId();
            bitField0_ = (bitField0_ & ~ 0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>string conversationId = 1;</code>
         *
         * @param value The bytes for conversationId to set.
         * @return This builder for chaining.
         */
        public Builder setConversationIdBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            conversationId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private int conversationType_;

        /**
         * <code>int32 conversationType = 2;</code>
         *
         * @return The conversationType.
         */
        @Override
        public int getConversationType() {
            return conversationType_;
        }

        /**
         * <code>int32 conversationType = 2;</code>
         *
         * @param value The conversationType to set.
         * @return This builder for chaining.
         */
        public Builder setConversationType(int value) {

            conversationType_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>int32 conversationType = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConversationType() {
            bitField0_ = (bitField0_ & ~ 0x00000002);
            conversationType_ = 0;
            onChanged();
            return this;
        }

        private long serverMessageId_;

        /**
         * <code>int64 serverMessageId = 3;</code>
         *
         * @return The serverMessageId.
         */
        @Override
        public long getServerMessageId() {
            return serverMessageId_;
        }

        /**
         * <code>int64 serverMessageId = 3;</code>
         *
         * @param value The serverMessageId to set.
         * @return This builder for chaining.
         */
        public Builder setServerMessageId(long value) {

            serverMessageId_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>int64 serverMessageId = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearServerMessageId() {
            bitField0_ = (bitField0_ & ~ 0x00000004);
            serverMessageId_ = 0L;
            onChanged();
            return this;
        }

        private long indexInConversation_;

        /**
         * <code>int64 indexInConversation = 4;</code>
         *
         * @return The indexInConversation.
         */
        @Override
        public long getIndexInConversation() {
            return indexInConversation_;
        }

        /**
         * <code>int64 indexInConversation = 4;</code>
         *
         * @param value The indexInConversation to set.
         * @return This builder for chaining.
         */
        public Builder setIndexInConversation(long value) {

            indexInConversation_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>int64 indexInConversation = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIndexInConversation() {
            bitField0_ = (bitField0_ & ~ 0x00000008);
            indexInConversation_ = 0L;
            onChanged();
            return this;
        }

        private long conversationShortId_;

        /**
         * <code>int64 conversationShortId = 5;</code>
         *
         * @return The conversationShortId.
         */
        @Override
        public long getConversationShortId() {
            return conversationShortId_;
        }

        /**
         * <code>int64 conversationShortId = 5;</code>
         *
         * @param value The conversationShortId to set.
         * @return This builder for chaining.
         */
        public Builder setConversationShortId(long value) {

            conversationShortId_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>int64 conversationShortId = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConversationShortId() {
            bitField0_ = (bitField0_ & ~ 0x00000010);
            conversationShortId_ = 0L;
            onChanged();
            return this;
        }

        private int messageType_;

        /**
         * <code>int32 messageType = 6;</code>
         *
         * @return The messageType.
         */
        @Override
        public int getMessageType() {
            return messageType_;
        }

        /**
         * <code>int32 messageType = 6;</code>
         *
         * @param value The messageType to set.
         * @return This builder for chaining.
         */
        public Builder setMessageType(int value) {

            messageType_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>int32 messageType = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMessageType() {
            bitField0_ = (bitField0_ & ~ 0x00000020);
            messageType_ = 0;
            onChanged();
            return this;
        }

        private long sender_;

        /**
         * <code>int64 sender = 7;</code>
         *
         * @return The sender.
         */
        @Override
        public long getSender() {
            return sender_;
        }

        /**
         * <code>int64 sender = 7;</code>
         *
         * @param value The sender to set.
         * @return This builder for chaining.
         */
        public Builder setSender(long value) {

            sender_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>int64 sender = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSender() {
            bitField0_ = (bitField0_ & ~ 0x00000040);
            sender_ = 0L;
            onChanged();
            return this;
        }

        private Object content_ = "";

        /**
         * <code>string content = 8;</code>
         *
         * @return The content.
         */
        public String getContent() {
            Object ref = content_;
            if(! (ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                content_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string content = 8;</code>
         *
         * @return The bytes for content.
         */
        public com.google.protobuf.ByteString
        getContentBytes()
        {
            Object ref = content_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string content = 8;</code>
         *
         * @param value The content to set.
         * @return This builder for chaining.
         */
        public Builder setContent(
                String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            content_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        /**
         * <code>string content = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContent() {
            content_ = getDefaultInstance().getContent();
            bitField0_ = (bitField0_ & ~ 0x00000080);
            onChanged();
            return this;
        }

        /**
         * <code>string content = 8;</code>
         *
         * @param value The bytes for content to set.
         * @return This builder for chaining.
         */
        public Builder setContentBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            content_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        private long createTime_;

        /**
         * <pre>
         * repeated Entity ext = 9;
         * </pre>
         *
         * <code>int64 createTime = 10;</code>
         *
         * @return The createTime.
         */
        @Override
        public long getCreateTime() {
            return createTime_;
        }

        /**
         * <pre>
         * repeated Entity ext = 9;
         * </pre>
         *
         * <code>int64 createTime = 10;</code>
         *
         * @param value The createTime to set.
         * @return This builder for chaining.
         */
        public Builder setCreateTime(long value) {

            createTime_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * repeated Entity ext = 9;
         * </pre>
         *
         * <code>int64 createTime = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCreateTime() {
            bitField0_ = (bitField0_ & ~ 0x00000100);
            createTime_ = 0L;
            onChanged();
            return this;
        }

        private long version_;

        /**
         * <code>int64 version = 11;</code>
         *
         * @return The version.
         */
        @Override
        public long getVersion() {
            return version_;
        }

        /**
         * <code>int64 version = 11;</code>
         *
         * @param value The version to set.
         * @return This builder for chaining.
         */
        public Builder setVersion(long value) {

            version_ = value;
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>int64 version = 11;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearVersion() {
            bitField0_ = (bitField0_ & ~ 0x00000200);
            version_ = 0L;
            onChanged();
            return this;
        }

        private int status_;

        /**
         * <code>int32 status = 12;</code>
         *
         * @return The status.
         */
        @Override
        public int getStatus() {
            return status_;
        }

        /**
         * <code>int32 status = 12;</code>
         *
         * @param value The status to set.
         * @return This builder for chaining.
         */
        public Builder setStatus(int value) {

            status_ = value;
            bitField0_ |= 0x00000400;
            onChanged();
            return this;
        }

        /**
         * <code>int32 status = 12;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStatus() {
            bitField0_ = (bitField0_ & ~ 0x00000400);
            status_ = 0;
            onChanged();
            return this;
        }

        private long orderInConversation_;

        /**
         * <code>int64 orderInConversation = 13;</code>
         *
         * @return The orderInConversation.
         */
        @Override
        public long getOrderInConversation() {
            return orderInConversation_;
        }

        /**
         * <code>int64 orderInConversation = 13;</code>
         *
         * @param value The orderInConversation to set.
         * @return This builder for chaining.
         */
        public Builder setOrderInConversation(long value) {

            orderInConversation_ = value;
            bitField0_ |= 0x00000800;
            onChanged();
            return this;
        }

        /**
         * <code>int64 orderInConversation = 13;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearOrderInConversation() {
            bitField0_ = (bitField0_ & ~ 0x00000800);
            orderInConversation_ = 0L;
            onChanged();
            return this;
        }

        private Object secSender_ = "";

        /**
         * <code>string secSender = 14;</code>
         *
         * @return The secSender.
         */
        public String getSecSender() {
            Object ref = secSender_;
            if(! (ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                secSender_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string secSender = 14;</code>
         *
         * @return The bytes for secSender.
         */
        public com.google.protobuf.ByteString
        getSecSenderBytes()
        {
            Object ref = secSender_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                secSender_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string secSender = 14;</code>
         *
         * @param value The secSender to set.
         * @return This builder for chaining.
         */
        public Builder setSecSender(
                String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            secSender_ = value;
            bitField0_ |= 0x00001000;
            onChanged();
            return this;
        }

        /**
         * <code>string secSender = 14;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSecSender() {
            secSender_ = getDefaultInstance().getSecSender();
            bitField0_ = (bitField0_ & ~ 0x00001000);
            onChanged();
            return this;
        }

        /**
         * <code>string secSender = 14;</code>
         *
         * @param value The bytes for secSender to set.
         * @return This builder for chaining.
         */
        public Builder setSecSenderBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            secSender_ = value;
            bitField0_ |= 0x00001000;
            onChanged();
            return this;
        }

        private long indexInConversationV2_;

        /**
         * <code>int64 indexInConversationV2 = 17;</code>
         *
         * @return The indexInConversationV2.
         */
        @Override
        public long getIndexInConversationV2() {
            return indexInConversationV2_;
        }

        /**
         * <code>int64 indexInConversationV2 = 17;</code>
         *
         * @param value The indexInConversationV2 to set.
         * @return This builder for chaining.
         */
        public Builder setIndexInConversationV2(long value) {

            indexInConversationV2_ = value;
            bitField0_ |= 0x00002000;
            onChanged();
            return this;
        }

        /**
         * <code>int64 indexInConversationV2 = 17;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIndexInConversationV2() {
            bitField0_ = (bitField0_ & ~ 0x00002000);
            indexInConversationV2_ = 0L;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:MessageBody)
    }

    // @@protoc_insertion_point(class_scope:MessageBody)
    private static final MessageBody DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new MessageBody();
    }

    public static MessageBody getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageBody>
            PARSER = new com.google.protobuf.AbstractParser<MessageBody>() {
        @Override
        public MessageBody parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch(com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch(java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<MessageBody> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageBody> getParserForType() {
        return PARSER;
    }

    @Override
    public MessageBody getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

