// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

public interface NewMessageNotifyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:NewMessageNotify)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string conversationId = 2;</code>
     *
     * @return The conversationId.
     */
    java.lang.String getConversationId();

    /**
     * <code>string conversationId = 2;</code>
     *
     * @return The bytes for conversationId.
     */
    com.google.protobuf.ByteString
    getConversationIdBytes();

    /**
     * <code>int32 conversationType = 3;</code>
     *
     * @return The conversationType.
     */
    int getConversationType();

    /**
     * <code>int32 notifyType = 4;</code>
     *
     * @return The notifyType.
     */
    int getNotifyType();

    /**
     * <code>.MessageBody message = 5;</code>
     *
     * @return Whether the message field is set.
     */
    boolean hasMessage();

    /**
     * <code>.MessageBody message = 5;</code>
     *
     * @return The message.
     */
    MessageBody getMessage();

    /**
     * <code>.MessageBody message = 5;</code>
     */
    MessageBodyOrBuilder getMessageOrBuilder();

    /**
     * <code>int64 previousCursor = 6;</code>
     *
     * @return The previousCursor.
     */
    long getPreviousCursor();

    /**
     * <code>int64 nextCursor = 7;</code>
     *
     * @return The nextCursor.
     */
    long getNextCursor();

    /**
     * <code>int64 indexInConversation = 8;</code>
     *
     * @return The indexInConversation.
     */
    long getIndexInConversation();

    /**
     * <code>int64 indexInConversation_v2 = 9;</code>
     *
     * @return The indexInConversationV2.
     */
    long getIndexInConversationV2();

    /**
     * <code>int64 conversationVersion = 10;</code>
     *
     * @return The conversationVersion.
     */
    long getConversationVersion();

    /**
     * <code>int64 previousConversationVersion = 11;</code>
     *
     * @return The previousConversationVersion.
     */
    long getPreviousConversationVersion();

    /**
     * <code>int64 cmdMessageIndex = 12;</code>
     *
     * @return The cmdMessageIndex.
     */
    long getCmdMessageIndex();

    /**
     * <code>int32 badgeCount = 13;</code>
     *
     * @return The badgeCount.
     */
    int getBadgeCount();
}
