// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

/**
 * Protobuf type {@code NewMessageNotify}
 */
public final class NewMessageNotify extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:NewMessageNotify)
        NewMessageNotifyOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                NewMessageNotify.class.getName());
    }

    // Use NewMessageNotify.newBuilder() to construct.
    private NewMessageNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private NewMessageNotify() {
        conversationId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor()
    {
        return ChatMessage.internal_static_NewMessageNotify_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable()
    {
        return ChatMessage.internal_static_NewMessageNotify_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        NewMessageNotify.class, Builder.class);
    }

    private int bitField0_;
    public static final int CONVERSATIONID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object conversationId_ = "";

    /**
     * <code>string conversationId = 2;</code>
     *
     * @return The conversationId.
     */
    @Override
    public String getConversationId() {
        Object ref = conversationId_;
        if(ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            conversationId_ = s;
            return s;
        }
    }

    /**
     * <code>string conversationId = 2;</code>
     *
     * @return The bytes for conversationId.
     */
    @Override
    public com.google.protobuf.ByteString
    getConversationIdBytes()
    {
        Object ref = conversationId_;
        if(ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            conversationId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CONVERSATIONTYPE_FIELD_NUMBER = 3;
    private int conversationType_ = 0;

    /**
     * <code>int32 conversationType = 3;</code>
     *
     * @return The conversationType.
     */
    @Override
    public int getConversationType() {
        return conversationType_;
    }

    public static final int NOTIFYTYPE_FIELD_NUMBER = 4;
    private int notifyType_ = 0;

    /**
     * <code>int32 notifyType = 4;</code>
     *
     * @return The notifyType.
     */
    @Override
    public int getNotifyType() {
        return notifyType_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private MessageBody message_;

    /**
     * <code>.MessageBody message = 5;</code>
     *
     * @return Whether the message field is set.
     */
    @Override
    public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.MessageBody message = 5;</code>
     *
     * @return The message.
     */
    @Override
    public MessageBody getMessage() {
        return message_ == null ? MessageBody.getDefaultInstance() : message_;
    }

    /**
     * <code>.MessageBody message = 5;</code>
     */
    @Override
    public MessageBodyOrBuilder getMessageOrBuilder() {
        return message_ == null ? MessageBody.getDefaultInstance() : message_;
    }

    public static final int PREVIOUSCURSOR_FIELD_NUMBER = 6;
    private long previousCursor_ = 0L;

    /**
     * <code>int64 previousCursor = 6;</code>
     *
     * @return The previousCursor.
     */
    @Override
    public long getPreviousCursor() {
        return previousCursor_;
    }

    public static final int NEXTCURSOR_FIELD_NUMBER = 7;
    private long nextCursor_ = 0L;

    /**
     * <code>int64 nextCursor = 7;</code>
     *
     * @return The nextCursor.
     */
    @Override
    public long getNextCursor() {
        return nextCursor_;
    }

    public static final int INDEXINCONVERSATION_FIELD_NUMBER = 8;
    private long indexInConversation_ = 0L;

    /**
     * <code>int64 indexInConversation = 8;</code>
     *
     * @return The indexInConversation.
     */
    @Override
    public long getIndexInConversation() {
        return indexInConversation_;
    }

    public static final int INDEXINCONVERSATION_V2_FIELD_NUMBER = 9;
    private long indexInConversationV2_ = 0L;

    /**
     * <code>int64 indexInConversation_v2 = 9;</code>
     *
     * @return The indexInConversationV2.
     */
    @Override
    public long getIndexInConversationV2() {
        return indexInConversationV2_;
    }

    public static final int CONVERSATIONVERSION_FIELD_NUMBER = 10;
    private long conversationVersion_ = 0L;

    /**
     * <code>int64 conversationVersion = 10;</code>
     *
     * @return The conversationVersion.
     */
    @Override
    public long getConversationVersion() {
        return conversationVersion_;
    }

    public static final int PREVIOUSCONVERSATIONVERSION_FIELD_NUMBER = 11;
    private long previousConversationVersion_ = 0L;

    /**
     * <code>int64 previousConversationVersion = 11;</code>
     *
     * @return The previousConversationVersion.
     */
    @Override
    public long getPreviousConversationVersion() {
        return previousConversationVersion_;
    }

    public static final int CMDMESSAGEINDEX_FIELD_NUMBER = 12;
    private long cmdMessageIndex_ = 0L;

    /**
     * <code>int64 cmdMessageIndex = 12;</code>
     *
     * @return The cmdMessageIndex.
     */
    @Override
    public long getCmdMessageIndex() {
        return cmdMessageIndex_;
    }

    public static final int BADGECOUNT_FIELD_NUMBER = 13;
    private int badgeCount_ = 0;

    /**
     * <code>int32 badgeCount = 13;</code>
     *
     * @return The badgeCount.
     */
    @Override
    public int getBadgeCount() {
        return badgeCount_;
    }

    private byte memoizedIsInitialized = - 1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if(isInitialized == 1) return true;
        if(isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException
    {
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(conversationId_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, conversationId_);
        }
        if(conversationType_ != 0) {
            output.writeInt32(3, conversationType_);
        }
        if(notifyType_ != 0) {
            output.writeInt32(4, notifyType_);
        }
        if(((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(5, getMessage());
        }
        if(previousCursor_ != 0L) {
            output.writeInt64(6, previousCursor_);
        }
        if(nextCursor_ != 0L) {
            output.writeInt64(7, nextCursor_);
        }
        if(indexInConversation_ != 0L) {
            output.writeInt64(8, indexInConversation_);
        }
        if(indexInConversationV2_ != 0L) {
            output.writeInt64(9, indexInConversationV2_);
        }
        if(conversationVersion_ != 0L) {
            output.writeInt64(10, conversationVersion_);
        }
        if(previousConversationVersion_ != 0L) {
            output.writeInt64(11, previousConversationVersion_);
        }
        if(cmdMessageIndex_ != 0L) {
            output.writeInt64(12, cmdMessageIndex_);
        }
        if(badgeCount_ != 0) {
            output.writeInt32(13, badgeCount_);
        }
        getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if(size != - 1) return size;

        size = 0;
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(conversationId_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, conversationId_);
        }
        if(conversationType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, conversationType_);
        }
        if(notifyType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, notifyType_);
        }
        if(((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, getMessage());
        }
        if(previousCursor_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(6, previousCursor_);
        }
        if(nextCursor_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(7, nextCursor_);
        }
        if(indexInConversation_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(8, indexInConversation_);
        }
        if(indexInConversationV2_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(9, indexInConversationV2_);
        }
        if(conversationVersion_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(10, conversationVersion_);
        }
        if(previousConversationVersion_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(11, previousConversationVersion_);
        }
        if(cmdMessageIndex_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(12, cmdMessageIndex_);
        }
        if(badgeCount_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(13, badgeCount_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if(obj == this) {
            return true;
        }
        if(! (obj instanceof NewMessageNotify)) {
            return super.equals(obj);
        }
        NewMessageNotify other = (NewMessageNotify) obj;

        if(! getConversationId()
                .equals(other.getConversationId())) return false;
        if(getConversationType()
                != other.getConversationType()) return false;
        if(getNotifyType()
                != other.getNotifyType()) return false;
        if(hasMessage() != other.hasMessage()) return false;
        if(hasMessage()) {
            if(! getMessage()
                    .equals(other.getMessage())) return false;
        }
        if(getPreviousCursor()
                != other.getPreviousCursor()) return false;
        if(getNextCursor()
                != other.getNextCursor()) return false;
        if(getIndexInConversation()
                != other.getIndexInConversation()) return false;
        if(getIndexInConversationV2()
                != other.getIndexInConversationV2()) return false;
        if(getConversationVersion()
                != other.getConversationVersion()) return false;
        if(getPreviousConversationVersion()
                != other.getPreviousConversationVersion()) return false;
        if(getCmdMessageIndex()
                != other.getCmdMessageIndex()) return false;
        if(getBadgeCount()
                != other.getBadgeCount()) return false;
        if(! getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if(memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CONVERSATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getConversationId().hashCode();
        hash = (37 * hash) + CONVERSATIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getConversationType();
        hash = (37 * hash) + NOTIFYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getNotifyType();
        if(hasMessage()) {
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
        }
        hash = (37 * hash) + PREVIOUSCURSOR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getPreviousCursor());
        hash = (37 * hash) + NEXTCURSOR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getNextCursor());
        hash = (37 * hash) + INDEXINCONVERSATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getIndexInConversation());
        hash = (37 * hash) + INDEXINCONVERSATION_V2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getIndexInConversationV2());
        hash = (37 * hash) + CONVERSATIONVERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getConversationVersion());
        hash = (37 * hash) + PREVIOUSCONVERSATIONVERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getPreviousConversationVersion());
        hash = (37 * hash) + CMDMESSAGEINDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getCmdMessageIndex());
        hash = (37 * hash) + BADGECOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getBadgeCount();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static NewMessageNotify parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static NewMessageNotify parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NewMessageNotify parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static NewMessageNotify parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NewMessageNotify parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static NewMessageNotify parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NewMessageNotify parseFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static NewMessageNotify parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NewMessageNotify parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static NewMessageNotify parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static NewMessageNotify parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static NewMessageNotify parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(NewMessageNotify prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent)
    {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code NewMessageNotify}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:NewMessageNotify)
            NewMessageNotifyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatMessage.internal_static_NewMessageNotify_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatMessage.internal_static_NewMessageNotify_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            NewMessageNotify.class, Builder.class);
        }

        // Construct using NewMessageNotify.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent)
        {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if(com.google.protobuf.GeneratedMessage
                    .alwaysUseFieldBuilders) {
                getMessageFieldBuilder();
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            conversationId_ = "";
            conversationType_ = 0;
            notifyType_ = 0;
            message_ = null;
            if(messageBuilder_ != null) {
                messageBuilder_.dispose();
                messageBuilder_ = null;
            }
            previousCursor_ = 0L;
            nextCursor_ = 0L;
            indexInConversation_ = 0L;
            indexInConversationV2_ = 0L;
            conversationVersion_ = 0L;
            previousConversationVersion_ = 0L;
            cmdMessageIndex_ = 0L;
            badgeCount_ = 0;
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType()
        {
            return ChatMessage.internal_static_NewMessageNotify_descriptor;
        }

        @Override
        public NewMessageNotify getDefaultInstanceForType() {
            return NewMessageNotify.getDefaultInstance();
        }

        @Override
        public NewMessageNotify build() {
            NewMessageNotify result = buildPartial();
            if(! result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public NewMessageNotify buildPartial() {
            NewMessageNotify result = new NewMessageNotify(this);
            if(bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(NewMessageNotify result) {
            int from_bitField0_ = bitField0_;
            if(((from_bitField0_ & 0x00000001) != 0)) {
                result.conversationId_ = conversationId_;
            }
            if(((from_bitField0_ & 0x00000002) != 0)) {
                result.conversationType_ = conversationType_;
            }
            if(((from_bitField0_ & 0x00000004) != 0)) {
                result.notifyType_ = notifyType_;
            }
            int to_bitField0_ = 0;
            if(((from_bitField0_ & 0x00000008) != 0)) {
                result.message_ = messageBuilder_ == null
                        ? message_
                        : messageBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if(((from_bitField0_ & 0x00000010) != 0)) {
                result.previousCursor_ = previousCursor_;
            }
            if(((from_bitField0_ & 0x00000020) != 0)) {
                result.nextCursor_ = nextCursor_;
            }
            if(((from_bitField0_ & 0x00000040) != 0)) {
                result.indexInConversation_ = indexInConversation_;
            }
            if(((from_bitField0_ & 0x00000080) != 0)) {
                result.indexInConversationV2_ = indexInConversationV2_;
            }
            if(((from_bitField0_ & 0x00000100) != 0)) {
                result.conversationVersion_ = conversationVersion_;
            }
            if(((from_bitField0_ & 0x00000200) != 0)) {
                result.previousConversationVersion_ = previousConversationVersion_;
            }
            if(((from_bitField0_ & 0x00000400) != 0)) {
                result.cmdMessageIndex_ = cmdMessageIndex_;
            }
            if(((from_bitField0_ & 0x00000800) != 0)) {
                result.badgeCount_ = badgeCount_;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if(other instanceof NewMessageNotify) {
                return mergeFrom((NewMessageNotify) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(NewMessageNotify other) {
            if(other == NewMessageNotify.getDefaultInstance()) return this;
            if(! other.getConversationId().isEmpty()) {
                conversationId_ = other.conversationId_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if(other.getConversationType() != 0) {
                setConversationType(other.getConversationType());
            }
            if(other.getNotifyType() != 0) {
                setNotifyType(other.getNotifyType());
            }
            if(other.hasMessage()) {
                mergeMessage(other.getMessage());
            }
            if(other.getPreviousCursor() != 0L) {
                setPreviousCursor(other.getPreviousCursor());
            }
            if(other.getNextCursor() != 0L) {
                setNextCursor(other.getNextCursor());
            }
            if(other.getIndexInConversation() != 0L) {
                setIndexInConversation(other.getIndexInConversation());
            }
            if(other.getIndexInConversationV2() != 0L) {
                setIndexInConversationV2(other.getIndexInConversationV2());
            }
            if(other.getConversationVersion() != 0L) {
                setConversationVersion(other.getConversationVersion());
            }
            if(other.getPreviousConversationVersion() != 0L) {
                setPreviousConversationVersion(other.getPreviousConversationVersion());
            }
            if(other.getCmdMessageIndex() != 0L) {
                setCmdMessageIndex(other.getCmdMessageIndex());
            }
            if(other.getBadgeCount() != 0) {
                setBadgeCount(other.getBadgeCount());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            if(extensionRegistry == null) {
                throw new NullPointerException();
            }
            try {
                boolean done = false;
                while(! done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 18: {
                            conversationId_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 18
                        case 24: {
                            conversationType_ = input.readInt32();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 24
                        case 32: {
                            notifyType_ = input.readInt32();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 32
                        case 42: {
                            input.readMessage(
                                    getMessageFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 42
                        case 48: {
                            previousCursor_ = input.readInt64();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 48
                        case 56: {
                            nextCursor_ = input.readInt64();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 56
                        case 64: {
                            indexInConversation_ = input.readInt64();
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 64
                        case 72: {
                            indexInConversationV2_ = input.readInt64();
                            bitField0_ |= 0x00000080;
                            break;
                        } // case 72
                        case 80: {
                            conversationVersion_ = input.readInt64();
                            bitField0_ |= 0x00000100;
                            break;
                        } // case 80
                        case 88: {
                            previousConversationVersion_ = input.readInt64();
                            bitField0_ |= 0x00000200;
                            break;
                        } // case 88
                        case 96: {
                            cmdMessageIndex_ = input.readInt64();
                            bitField0_ |= 0x00000400;
                            break;
                        } // case 96
                        case 104: {
                            badgeCount_ = input.readInt32();
                            bitField0_ |= 0x00000800;
                            break;
                        } // case 104
                        default: {
                            if(! super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private Object conversationId_ = "";

        /**
         * <code>string conversationId = 2;</code>
         *
         * @return The conversationId.
         */
        public String getConversationId() {
            Object ref = conversationId_;
            if(! (ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                conversationId_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string conversationId = 2;</code>
         *
         * @return The bytes for conversationId.
         */
        public com.google.protobuf.ByteString
        getConversationIdBytes()
        {
            Object ref = conversationId_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                conversationId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string conversationId = 2;</code>
         *
         * @param value The conversationId to set.
         * @return This builder for chaining.
         */
        public Builder setConversationId(
                String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            conversationId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string conversationId = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConversationId() {
            conversationId_ = getDefaultInstance().getConversationId();
            bitField0_ = (bitField0_ & ~ 0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>string conversationId = 2;</code>
         *
         * @param value The bytes for conversationId to set.
         * @return This builder for chaining.
         */
        public Builder setConversationIdBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            conversationId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private int conversationType_;

        /**
         * <code>int32 conversationType = 3;</code>
         *
         * @return The conversationType.
         */
        @Override
        public int getConversationType() {
            return conversationType_;
        }

        /**
         * <code>int32 conversationType = 3;</code>
         *
         * @param value The conversationType to set.
         * @return This builder for chaining.
         */
        public Builder setConversationType(int value) {

            conversationType_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>int32 conversationType = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConversationType() {
            bitField0_ = (bitField0_ & ~ 0x00000002);
            conversationType_ = 0;
            onChanged();
            return this;
        }

        private int notifyType_;

        /**
         * <code>int32 notifyType = 4;</code>
         *
         * @return The notifyType.
         */
        @Override
        public int getNotifyType() {
            return notifyType_;
        }

        /**
         * <code>int32 notifyType = 4;</code>
         *
         * @param value The notifyType to set.
         * @return This builder for chaining.
         */
        public Builder setNotifyType(int value) {

            notifyType_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>int32 notifyType = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearNotifyType() {
            bitField0_ = (bitField0_ & ~ 0x00000004);
            notifyType_ = 0;
            onChanged();
            return this;
        }

        private MessageBody message_;
        private com.google.protobuf.SingleFieldBuilder<
                MessageBody, MessageBody.Builder, MessageBodyOrBuilder> messageBuilder_;

        /**
         * <code>.MessageBody message = 5;</code>
         *
         * @return Whether the message field is set.
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>.MessageBody message = 5;</code>
         *
         * @return The message.
         */
        public MessageBody getMessage() {
            if(messageBuilder_ == null) {
                return message_ == null ? MessageBody.getDefaultInstance() : message_;
            } else {
                return messageBuilder_.getMessage();
            }
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        public Builder setMessage(MessageBody value) {
            if(messageBuilder_ == null) {
                if(value == null) {
                    throw new NullPointerException();
                }
                message_ = value;
            } else {
                messageBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        public Builder setMessage(
                MessageBody.Builder builderForValue)
        {
            if(messageBuilder_ == null) {
                message_ = builderForValue.build();
            } else {
                messageBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        public Builder mergeMessage(MessageBody value) {
            if(messageBuilder_ == null) {
                if(((bitField0_ & 0x00000008) != 0) &&
                        message_ != null &&
                        message_ != MessageBody.getDefaultInstance()) {
                    getMessageBuilder().mergeFrom(value);
                } else {
                    message_ = value;
                }
            } else {
                messageBuilder_.mergeFrom(value);
            }
            if(message_ != null) {
                bitField0_ |= 0x00000008;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        public Builder clearMessage() {
            bitField0_ = (bitField0_ & ~ 0x00000008);
            message_ = null;
            if(messageBuilder_ != null) {
                messageBuilder_.dispose();
                messageBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        public MessageBody.Builder getMessageBuilder() {
            bitField0_ |= 0x00000008;
            onChanged();
            return getMessageFieldBuilder().getBuilder();
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        public MessageBodyOrBuilder getMessageOrBuilder() {
            if(messageBuilder_ != null) {
                return messageBuilder_.getMessageOrBuilder();
            } else {
                return message_ == null ?
                        MessageBody.getDefaultInstance() : message_;
            }
        }

        /**
         * <code>.MessageBody message = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
                MessageBody, MessageBody.Builder, MessageBodyOrBuilder>
        getMessageFieldBuilder()
        {
            if(messageBuilder_ == null) {
                messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                        MessageBody, MessageBody.Builder, MessageBodyOrBuilder>(
                        getMessage(),
                        getParentForChildren(),
                        isClean());
                message_ = null;
            }
            return messageBuilder_;
        }

        private long previousCursor_;

        /**
         * <code>int64 previousCursor = 6;</code>
         *
         * @return The previousCursor.
         */
        @Override
        public long getPreviousCursor() {
            return previousCursor_;
        }

        /**
         * <code>int64 previousCursor = 6;</code>
         *
         * @param value The previousCursor to set.
         * @return This builder for chaining.
         */
        public Builder setPreviousCursor(long value) {

            previousCursor_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>int64 previousCursor = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPreviousCursor() {
            bitField0_ = (bitField0_ & ~ 0x00000010);
            previousCursor_ = 0L;
            onChanged();
            return this;
        }

        private long nextCursor_;

        /**
         * <code>int64 nextCursor = 7;</code>
         *
         * @return The nextCursor.
         */
        @Override
        public long getNextCursor() {
            return nextCursor_;
        }

        /**
         * <code>int64 nextCursor = 7;</code>
         *
         * @param value The nextCursor to set.
         * @return This builder for chaining.
         */
        public Builder setNextCursor(long value) {

            nextCursor_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>int64 nextCursor = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearNextCursor() {
            bitField0_ = (bitField0_ & ~ 0x00000020);
            nextCursor_ = 0L;
            onChanged();
            return this;
        }

        private long indexInConversation_;

        /**
         * <code>int64 indexInConversation = 8;</code>
         *
         * @return The indexInConversation.
         */
        @Override
        public long getIndexInConversation() {
            return indexInConversation_;
        }

        /**
         * <code>int64 indexInConversation = 8;</code>
         *
         * @param value The indexInConversation to set.
         * @return This builder for chaining.
         */
        public Builder setIndexInConversation(long value) {

            indexInConversation_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>int64 indexInConversation = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIndexInConversation() {
            bitField0_ = (bitField0_ & ~ 0x00000040);
            indexInConversation_ = 0L;
            onChanged();
            return this;
        }

        private long indexInConversationV2_;

        /**
         * <code>int64 indexInConversation_v2 = 9;</code>
         *
         * @return The indexInConversationV2.
         */
        @Override
        public long getIndexInConversationV2() {
            return indexInConversationV2_;
        }

        /**
         * <code>int64 indexInConversation_v2 = 9;</code>
         *
         * @param value The indexInConversationV2 to set.
         * @return This builder for chaining.
         */
        public Builder setIndexInConversationV2(long value) {

            indexInConversationV2_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        /**
         * <code>int64 indexInConversation_v2 = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIndexInConversationV2() {
            bitField0_ = (bitField0_ & ~ 0x00000080);
            indexInConversationV2_ = 0L;
            onChanged();
            return this;
        }

        private long conversationVersion_;

        /**
         * <code>int64 conversationVersion = 10;</code>
         *
         * @return The conversationVersion.
         */
        @Override
        public long getConversationVersion() {
            return conversationVersion_;
        }

        /**
         * <code>int64 conversationVersion = 10;</code>
         *
         * @param value The conversationVersion to set.
         * @return This builder for chaining.
         */
        public Builder setConversationVersion(long value) {

            conversationVersion_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        /**
         * <code>int64 conversationVersion = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConversationVersion() {
            bitField0_ = (bitField0_ & ~ 0x00000100);
            conversationVersion_ = 0L;
            onChanged();
            return this;
        }

        private long previousConversationVersion_;

        /**
         * <code>int64 previousConversationVersion = 11;</code>
         *
         * @return The previousConversationVersion.
         */
        @Override
        public long getPreviousConversationVersion() {
            return previousConversationVersion_;
        }

        /**
         * <code>int64 previousConversationVersion = 11;</code>
         *
         * @param value The previousConversationVersion to set.
         * @return This builder for chaining.
         */
        public Builder setPreviousConversationVersion(long value) {

            previousConversationVersion_ = value;
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>int64 previousConversationVersion = 11;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPreviousConversationVersion() {
            bitField0_ = (bitField0_ & ~ 0x00000200);
            previousConversationVersion_ = 0L;
            onChanged();
            return this;
        }

        private long cmdMessageIndex_;

        /**
         * <code>int64 cmdMessageIndex = 12;</code>
         *
         * @return The cmdMessageIndex.
         */
        @Override
        public long getCmdMessageIndex() {
            return cmdMessageIndex_;
        }

        /**
         * <code>int64 cmdMessageIndex = 12;</code>
         *
         * @param value The cmdMessageIndex to set.
         * @return This builder for chaining.
         */
        public Builder setCmdMessageIndex(long value) {

            cmdMessageIndex_ = value;
            bitField0_ |= 0x00000400;
            onChanged();
            return this;
        }

        /**
         * <code>int64 cmdMessageIndex = 12;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCmdMessageIndex() {
            bitField0_ = (bitField0_ & ~ 0x00000400);
            cmdMessageIndex_ = 0L;
            onChanged();
            return this;
        }

        private int badgeCount_;

        /**
         * <code>int32 badgeCount = 13;</code>
         *
         * @return The badgeCount.
         */
        @Override
        public int getBadgeCount() {
            return badgeCount_;
        }

        /**
         * <code>int32 badgeCount = 13;</code>
         *
         * @param value The badgeCount to set.
         * @return This builder for chaining.
         */
        public Builder setBadgeCount(int value) {

            badgeCount_ = value;
            bitField0_ |= 0x00000800;
            onChanged();
            return this;
        }

        /**
         * <code>int32 badgeCount = 13;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBadgeCount() {
            bitField0_ = (bitField0_ & ~ 0x00000800);
            badgeCount_ = 0;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:NewMessageNotify)
    }

    // @@protoc_insertion_point(class_scope:NewMessageNotify)
    private static final NewMessageNotify DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new NewMessageNotify();
    }

    public static NewMessageNotify getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewMessageNotify>
            PARSER = new com.google.protobuf.AbstractParser<NewMessageNotify>() {
        @Override
        public NewMessageNotify parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch(com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch(java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<NewMessageNotify> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NewMessageNotify> getParserForType() {
        return PARSER;
    }

    @Override
    public NewMessageNotify getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

