// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

/**
 * Protobuf type {@code PushFrame}
 */
public final class PushFrame extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:PushFrame)
        PushFrameOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                PushFrame.class.getName());
    }

    // Use PushFrame.newBuilder() to construct.
    private PushFrame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private PushFrame() {
        headers_ = java.util.Collections.emptyList();
        payloadEncoding_ = "";
        payloadType_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
        lodIdNew_ = "";
        serverTiming_ = "";
        msgID_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor()
    {
        return ChatMessage.internal_static_PushFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable()
    {
        return ChatMessage.internal_static_PushFrame_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PushFrame.class, PushFrame.Builder.class);
    }

    public static final int SEQID_FIELD_NUMBER = 1;
    private long seqID_ = 0L;

    /**
     * <code>uint64 seqID = 1;</code>
     *
     * @return The seqID.
     */
    @java.lang.Override
    public long getSeqID() {
        return seqID_;
    }

    public static final int LOGID_FIELD_NUMBER = 2;
    private long logID_ = 0L;

    /**
     * <code>uint64 logID = 2;</code>
     *
     * @return The logID.
     */
    @java.lang.Override
    public long getLogID() {
        return logID_;
    }

    public static final int SERVICE_FIELD_NUMBER = 3;
    private int service_ = 0;

    /**
     * <code>int32 service = 3;</code>
     *
     * @return The service.
     */
    @java.lang.Override
    public int getService() {
        return service_;
    }

    public static final int METHOD_FIELD_NUMBER = 4;
    private int method_ = 0;

    /**
     * <code>int32 method = 4;</code>
     *
     * @return The method.
     */
    @java.lang.Override
    public int getMethod() {
        return method_;
    }

    public static final int HEADERS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<Header> headers_;

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    @java.lang.Override
    public java.util.List<Header> getHeadersList() {
        return headers_;
    }

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends HeaderOrBuilder>
    getHeadersOrBuilderList()
    {
        return headers_;
    }

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    @java.lang.Override
    public int getHeadersCount() {
        return headers_.size();
    }

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    @java.lang.Override
    public Header getHeaders(int index) {
        return headers_.get(index);
    }

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    @java.lang.Override
    public HeaderOrBuilder getHeadersOrBuilder(
            int index)
    {
        return headers_.get(index);
    }

    public static final int PAYLOADENCODING_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object payloadEncoding_ = "";

    /**
     * <code>string payloadEncoding = 6;</code>
     *
     * @return The payloadEncoding.
     */
    @java.lang.Override
    public java.lang.String getPayloadEncoding() {
        java.lang.Object ref = payloadEncoding_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            payloadEncoding_ = s;
            return s;
        }
    }

    /**
     * <code>string payloadEncoding = 6;</code>
     *
     * @return The bytes for payloadEncoding.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getPayloadEncodingBytes()
    {
        java.lang.Object ref = payloadEncoding_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            payloadEncoding_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PAYLOADTYPE_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object payloadType_ = "";

    /**
     * <code>string payloadType = 7;</code>
     *
     * @return The payloadType.
     */
    @java.lang.Override
    public java.lang.String getPayloadType() {
        java.lang.Object ref = payloadType_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            payloadType_ = s;
            return s;
        }
    }

    /**
     * <code>string payloadType = 7;</code>
     *
     * @return The bytes for payloadType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getPayloadTypeBytes()
    {
        java.lang.Object ref = payloadType_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            payloadType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;

    /**
     * <code>bytes payload = 8;</code>
     *
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
        return payload_;
    }

    public static final int LODIDNEW_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lodIdNew_ = "";

    /**
     * <code>string lodIdNew = 9;</code>
     *
     * @return The lodIdNew.
     */
    @java.lang.Override
    public java.lang.String getLodIdNew() {
        java.lang.Object ref = lodIdNew_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            lodIdNew_ = s;
            return s;
        }
    }

    /**
     * <code>string lodIdNew = 9;</code>
     *
     * @return The bytes for lodIdNew.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getLodIdNewBytes()
    {
        java.lang.Object ref = lodIdNew_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            lodIdNew_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SERVERTIMING_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serverTiming_ = "";

    /**
     * <code>string serverTiming = 10;</code>
     *
     * @return The serverTiming.
     */
    @java.lang.Override
    public java.lang.String getServerTiming() {
        java.lang.Object ref = serverTiming_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            serverTiming_ = s;
            return s;
        }
    }

    /**
     * <code>string serverTiming = 10;</code>
     *
     * @return The bytes for serverTiming.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getServerTimingBytes()
    {
        java.lang.Object ref = serverTiming_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            serverTiming_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MSGID_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object msgID_ = "";

    /**
     * <code>string msgID = 11;</code>
     *
     * @return The msgID.
     */
    @java.lang.Override
    public java.lang.String getMsgID() {
        java.lang.Object ref = msgID_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msgID_ = s;
            return s;
        }
    }

    /**
     * <code>string msgID = 11;</code>
     *
     * @return The bytes for msgID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getMsgIDBytes()
    {
        java.lang.Object ref = msgID_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            msgID_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int FRAMETYPE_FIELD_NUMBER = 12;
    private int frameType_ = 0;

    /**
     * <code>int32 frameType = 12;</code>
     *
     * @return The frameType.
     */
    @java.lang.Override
    public int getFrameType() {
        return frameType_;
    }

    private byte memoizedIsInitialized = - 1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if(isInitialized == 1) return true;
        if(isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException
    {
        if(seqID_ != 0L) {
            output.writeUInt64(1, seqID_);
        }
        if(logID_ != 0L) {
            output.writeUInt64(2, logID_);
        }
        if(service_ != 0) {
            output.writeInt32(3, service_);
        }
        if(method_ != 0) {
            output.writeInt32(4, method_);
        }
        for(int i = 0; i < headers_.size(); i++) {
            output.writeMessage(5, headers_.get(i));
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(payloadEncoding_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 6, payloadEncoding_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(payloadType_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 7, payloadType_);
        }
        if(! payload_.isEmpty()) {
            output.writeBytes(8, payload_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(lodIdNew_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 9, lodIdNew_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(serverTiming_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 10, serverTiming_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(msgID_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 11, msgID_);
        }
        if(frameType_ != 0) {
            output.writeInt32(12, frameType_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if(size != - 1) return size;

        size = 0;
        if(seqID_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(1, seqID_);
        }
        if(logID_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(2, logID_);
        }
        if(service_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, service_);
        }
        if(method_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, method_);
        }
        for(int i = 0; i < headers_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, headers_.get(i));
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(payloadEncoding_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(6, payloadEncoding_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(payloadType_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(7, payloadType_);
        }
        if(! payload_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(8, payload_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(lodIdNew_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(9, lodIdNew_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(serverTiming_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(10, serverTiming_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(msgID_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(11, msgID_);
        }
        if(frameType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(12, frameType_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if(obj == this) {
            return true;
        }
        if(! (obj instanceof PushFrame)) {
            return super.equals(obj);
        }
        PushFrame other = (PushFrame) obj;

        if(getSeqID()
                != other.getSeqID()) return false;
        if(getLogID()
                != other.getLogID()) return false;
        if(getService()
                != other.getService()) return false;
        if(getMethod()
                != other.getMethod()) return false;
        if(! getHeadersList()
                .equals(other.getHeadersList())) return false;
        if(! getPayloadEncoding()
                .equals(other.getPayloadEncoding())) return false;
        if(! getPayloadType()
                .equals(other.getPayloadType())) return false;
        if(! getPayload()
                .equals(other.getPayload())) return false;
        if(! getLodIdNew()
                .equals(other.getLodIdNew())) return false;
        if(! getServerTiming()
                .equals(other.getServerTiming())) return false;
        if(! getMsgID()
                .equals(other.getMsgID())) return false;
        if(getFrameType()
                != other.getFrameType()) return false;
        if(! getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if(memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SEQID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getSeqID());
        hash = (37 * hash) + LOGID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getLogID());
        hash = (37 * hash) + SERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getService();
        hash = (37 * hash) + METHOD_FIELD_NUMBER;
        hash = (53 * hash) + getMethod();
        if(getHeadersCount() > 0) {
            hash = (37 * hash) + HEADERS_FIELD_NUMBER;
            hash = (53 * hash) + getHeadersList().hashCode();
        }
        hash = (37 * hash) + PAYLOADENCODING_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadEncoding().hashCode();
        hash = (37 * hash) + PAYLOADTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadType().hashCode();
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
        hash = (37 * hash) + LODIDNEW_FIELD_NUMBER;
        hash = (53 * hash) + getLodIdNew().hashCode();
        hash = (37 * hash) + SERVERTIMING_FIELD_NUMBER;
        hash = (53 * hash) + getServerTiming().hashCode();
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgID().hashCode();
        hash = (37 * hash) + FRAMETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getFrameType();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static PushFrame parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static PushFrame parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PushFrame parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static PushFrame parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PushFrame parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static PushFrame parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PushFrame parseFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static PushFrame parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PushFrame parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static PushFrame parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static PushFrame parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static PushFrame parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(PushFrame prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent)
    {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code PushFrame}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:PushFrame)
            PushFrameOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatMessage.internal_static_PushFrame_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatMessage.internal_static_PushFrame_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PushFrame.class, PushFrame.Builder.class);
        }

        // Construct using PushFrame.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent)
        {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            seqID_ = 0L;
            logID_ = 0L;
            service_ = 0;
            method_ = 0;
            if(headersBuilder_ == null) {
                headers_ = java.util.Collections.emptyList();
            } else {
                headers_ = null;
                headersBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~ 0x00000010);
            payloadEncoding_ = "";
            payloadType_ = "";
            payload_ = com.google.protobuf.ByteString.EMPTY;
            lodIdNew_ = "";
            serverTiming_ = "";
            msgID_ = "";
            frameType_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType()
        {
            return ChatMessage.internal_static_PushFrame_descriptor;
        }

        @java.lang.Override
        public PushFrame getDefaultInstanceForType() {
            return PushFrame.getDefaultInstance();
        }

        @java.lang.Override
        public PushFrame build() {
            PushFrame result = buildPartial();
            if(! result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public PushFrame buildPartial() {
            PushFrame result = new PushFrame(this);
            buildPartialRepeatedFields(result);
            if(bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(PushFrame result) {
            if(headersBuilder_ == null) {
                if(((bitField0_ & 0x00000010) != 0)) {
                    headers_ = java.util.Collections.unmodifiableList(headers_);
                    bitField0_ = (bitField0_ & ~ 0x00000010);
                }
                result.headers_ = headers_;
            } else {
                result.headers_ = headersBuilder_.build();
            }
        }

        private void buildPartial0(PushFrame result) {
            int from_bitField0_ = bitField0_;
            if(((from_bitField0_ & 0x00000001) != 0)) {
                result.seqID_ = seqID_;
            }
            if(((from_bitField0_ & 0x00000002) != 0)) {
                result.logID_ = logID_;
            }
            if(((from_bitField0_ & 0x00000004) != 0)) {
                result.service_ = service_;
            }
            if(((from_bitField0_ & 0x00000008) != 0)) {
                result.method_ = method_;
            }
            if(((from_bitField0_ & 0x00000020) != 0)) {
                result.payloadEncoding_ = payloadEncoding_;
            }
            if(((from_bitField0_ & 0x00000040) != 0)) {
                result.payloadType_ = payloadType_;
            }
            if(((from_bitField0_ & 0x00000080) != 0)) {
                result.payload_ = payload_;
            }
            if(((from_bitField0_ & 0x00000100) != 0)) {
                result.lodIdNew_ = lodIdNew_;
            }
            if(((from_bitField0_ & 0x00000200) != 0)) {
                result.serverTiming_ = serverTiming_;
            }
            if(((from_bitField0_ & 0x00000400) != 0)) {
                result.msgID_ = msgID_;
            }
            if(((from_bitField0_ & 0x00000800) != 0)) {
                result.frameType_ = frameType_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if(other instanceof PushFrame) {
                return mergeFrom((PushFrame) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(PushFrame other) {
            if(other == PushFrame.getDefaultInstance()) return this;
            if(other.getSeqID() != 0L) {
                setSeqID(other.getSeqID());
            }
            if(other.getLogID() != 0L) {
                setLogID(other.getLogID());
            }
            if(other.getService() != 0) {
                setService(other.getService());
            }
            if(other.getMethod() != 0) {
                setMethod(other.getMethod());
            }
            if(headersBuilder_ == null) {
                if(! other.headers_.isEmpty()) {
                    if(headers_.isEmpty()) {
                        headers_ = other.headers_;
                        bitField0_ = (bitField0_ & ~ 0x00000010);
                    } else {
                        ensureHeadersIsMutable();
                        headers_.addAll(other.headers_);
                    }
                    onChanged();
                }
            } else {
                if(! other.headers_.isEmpty()) {
                    if(headersBuilder_.isEmpty()) {
                        headersBuilder_.dispose();
                        headersBuilder_ = null;
                        headers_ = other.headers_;
                        bitField0_ = (bitField0_ & ~ 0x00000010);
                        headersBuilder_ =
                                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                        getHeadersFieldBuilder() : null;
                    } else {
                        headersBuilder_.addAllMessages(other.headers_);
                    }
                }
            }
            if(! other.getPayloadEncoding().isEmpty()) {
                payloadEncoding_ = other.payloadEncoding_;
                bitField0_ |= 0x00000020;
                onChanged();
            }
            if(! other.getPayloadType().isEmpty()) {
                payloadType_ = other.payloadType_;
                bitField0_ |= 0x00000040;
                onChanged();
            }
            if(other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
                setPayload(other.getPayload());
            }
            if(! other.getLodIdNew().isEmpty()) {
                lodIdNew_ = other.lodIdNew_;
                bitField0_ |= 0x00000100;
                onChanged();
            }
            if(! other.getServerTiming().isEmpty()) {
                serverTiming_ = other.serverTiming_;
                bitField0_ |= 0x00000200;
                onChanged();
            }
            if(! other.getMsgID().isEmpty()) {
                msgID_ = other.msgID_;
                bitField0_ |= 0x00000400;
                onChanged();
            }
            if(other.getFrameType() != 0) {
                setFrameType(other.getFrameType());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            if(extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while(! done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            seqID_ = input.readUInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 16: {
                            logID_ = input.readUInt64();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        case 24: {
                            service_ = input.readInt32();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 32: {
                            method_ = input.readInt32();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 32
                        case 42: {
                            Header m =
                                    input.readMessage(
                                            Header.parser(),
                                            extensionRegistry);
                            if(headersBuilder_ == null) {
                                ensureHeadersIsMutable();
                                headers_.add(m);
                            } else {
                                headersBuilder_.addMessage(m);
                            }
                            break;
                        } // case 42
                        case 50: {
                            payloadEncoding_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 50
                        case 58: {
                            payloadType_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 58
                        case 66: {
                            payload_ = input.readBytes();
                            bitField0_ |= 0x00000080;
                            break;
                        } // case 66
                        case 74: {
                            lodIdNew_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000100;
                            break;
                        } // case 74
                        case 82: {
                            serverTiming_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000200;
                            break;
                        } // case 82
                        case 90: {
                            msgID_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000400;
                            break;
                        } // case 90
                        case 96: {
                            frameType_ = input.readInt32();
                            bitField0_ |= 0x00000800;
                            break;
                        } // case 96
                        default: {
                            if(! super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private long seqID_;

        /**
         * <code>uint64 seqID = 1;</code>
         *
         * @return The seqID.
         */
        @java.lang.Override
        public long getSeqID() {
            return seqID_;
        }

        /**
         * <code>uint64 seqID = 1;</code>
         *
         * @param value The seqID to set.
         * @return This builder for chaining.
         */
        public Builder setSeqID(long value) {

            seqID_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 seqID = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSeqID() {
            bitField0_ = (bitField0_ & ~ 0x00000001);
            seqID_ = 0L;
            onChanged();
            return this;
        }

        private long logID_;

        /**
         * <code>uint64 logID = 2;</code>
         *
         * @return The logID.
         */
        @java.lang.Override
        public long getLogID() {
            return logID_;
        }

        /**
         * <code>uint64 logID = 2;</code>
         *
         * @param value The logID to set.
         * @return This builder for chaining.
         */
        public Builder setLogID(long value) {

            logID_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 logID = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLogID() {
            bitField0_ = (bitField0_ & ~ 0x00000002);
            logID_ = 0L;
            onChanged();
            return this;
        }

        private int service_;

        /**
         * <code>int32 service = 3;</code>
         *
         * @return The service.
         */
        @java.lang.Override
        public int getService() {
            return service_;
        }

        /**
         * <code>int32 service = 3;</code>
         *
         * @param value The service to set.
         * @return This builder for chaining.
         */
        public Builder setService(int value) {

            service_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>int32 service = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearService() {
            bitField0_ = (bitField0_ & ~ 0x00000004);
            service_ = 0;
            onChanged();
            return this;
        }

        private int method_;

        /**
         * <code>int32 method = 4;</code>
         *
         * @return The method.
         */
        @java.lang.Override
        public int getMethod() {
            return method_;
        }

        /**
         * <code>int32 method = 4;</code>
         *
         * @param value The method to set.
         * @return This builder for chaining.
         */
        public Builder setMethod(int value) {

            method_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>int32 method = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMethod() {
            bitField0_ = (bitField0_ & ~ 0x00000008);
            method_ = 0;
            onChanged();
            return this;
        }

        private java.util.List<Header> headers_ =
                java.util.Collections.emptyList();

        private void ensureHeadersIsMutable() {
            if(! ((bitField0_ & 0x00000010) != 0)) {
                headers_ = new java.util.ArrayList<Header>(headers_);
                bitField0_ |= 0x00000010;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                Header, Header.Builder, HeaderOrBuilder> headersBuilder_;

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public java.util.List<Header> getHeadersList() {
            if(headersBuilder_ == null) {
                return java.util.Collections.unmodifiableList(headers_);
            } else {
                return headersBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public int getHeadersCount() {
            if(headersBuilder_ == null) {
                return headers_.size();
            } else {
                return headersBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Header getHeaders(int index) {
            if(headersBuilder_ == null) {
                return headers_.get(index);
            } else {
                return headersBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder setHeaders(
                int index, Header value)
        {
            if(headersBuilder_ == null) {
                if(value == null) {
                    throw new NullPointerException();
                }
                ensureHeadersIsMutable();
                headers_.set(index, value);
                onChanged();
            } else {
                headersBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder setHeaders(
                int index, Header.Builder builderForValue)
        {
            if(headersBuilder_ == null) {
                ensureHeadersIsMutable();
                headers_.set(index, builderForValue.build());
                onChanged();
            } else {
                headersBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder addHeaders(Header value) {
            if(headersBuilder_ == null) {
                if(value == null) {
                    throw new NullPointerException();
                }
                ensureHeadersIsMutable();
                headers_.add(value);
                onChanged();
            } else {
                headersBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder addHeaders(
                int index, Header value)
        {
            if(headersBuilder_ == null) {
                if(value == null) {
                    throw new NullPointerException();
                }
                ensureHeadersIsMutable();
                headers_.add(index, value);
                onChanged();
            } else {
                headersBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder addHeaders(
                Header.Builder builderForValue)
        {
            if(headersBuilder_ == null) {
                ensureHeadersIsMutable();
                headers_.add(builderForValue.build());
                onChanged();
            } else {
                headersBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder addHeaders(
                int index, Header.Builder builderForValue)
        {
            if(headersBuilder_ == null) {
                ensureHeadersIsMutable();
                headers_.add(index, builderForValue.build());
                onChanged();
            } else {
                headersBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder addAllHeaders(
                java.lang.Iterable<? extends Header> values)
        {
            if(headersBuilder_ == null) {
                ensureHeadersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, headers_);
                onChanged();
            } else {
                headersBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder clearHeaders() {
            if(headersBuilder_ == null) {
                headers_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~ 0x00000010);
                onChanged();
            } else {
                headersBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Builder removeHeaders(int index) {
            if(headersBuilder_ == null) {
                ensureHeadersIsMutable();
                headers_.remove(index);
                onChanged();
            } else {
                headersBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Header.Builder getHeadersBuilder(
                int index)
        {
            return getHeadersFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public HeaderOrBuilder getHeadersOrBuilder(
                int index)
        {
            if(headersBuilder_ == null) {
                return headers_.get(index);
            } else {
                return headersBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public java.util.List<? extends HeaderOrBuilder>
        getHeadersOrBuilderList()
        {
            if(headersBuilder_ != null) {
                return headersBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(headers_);
            }
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Header.Builder addHeadersBuilder() {
            return getHeadersFieldBuilder().addBuilder(
                    Header.getDefaultInstance());
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public Header.Builder addHeadersBuilder(
                int index)
        {
            return getHeadersFieldBuilder().addBuilder(
                    index, Header.getDefaultInstance());
        }

        /**
         * <code>repeated .Header headers = 5;</code>
         */
        public java.util.List<Header.Builder>
        getHeadersBuilderList()
        {
            return getHeadersFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                Header, Header.Builder, HeaderOrBuilder>
        getHeadersFieldBuilder()
        {
            if(headersBuilder_ == null) {
                headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                        Header, Header.Builder, HeaderOrBuilder>(
                        headers_,
                        ((bitField0_ & 0x00000010) != 0),
                        getParentForChildren(),
                        isClean());
                headers_ = null;
            }
            return headersBuilder_;
        }

        private java.lang.Object payloadEncoding_ = "";

        /**
         * <code>string payloadEncoding = 6;</code>
         *
         * @return The payloadEncoding.
         */
        public java.lang.String getPayloadEncoding() {
            java.lang.Object ref = payloadEncoding_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                payloadEncoding_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string payloadEncoding = 6;</code>
         *
         * @return The bytes for payloadEncoding.
         */
        public com.google.protobuf.ByteString
        getPayloadEncodingBytes()
        {
            java.lang.Object ref = payloadEncoding_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                payloadEncoding_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string payloadEncoding = 6;</code>
         *
         * @param value The payloadEncoding to set.
         * @return This builder for chaining.
         */
        public Builder setPayloadEncoding(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            payloadEncoding_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>string payloadEncoding = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPayloadEncoding() {
            payloadEncoding_ = getDefaultInstance().getPayloadEncoding();
            bitField0_ = (bitField0_ & ~ 0x00000020);
            onChanged();
            return this;
        }

        /**
         * <code>string payloadEncoding = 6;</code>
         *
         * @param value The bytes for payloadEncoding to set.
         * @return This builder for chaining.
         */
        public Builder setPayloadEncodingBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            payloadEncoding_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        private java.lang.Object payloadType_ = "";

        /**
         * <code>string payloadType = 7;</code>
         *
         * @return The payloadType.
         */
        public java.lang.String getPayloadType() {
            java.lang.Object ref = payloadType_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                payloadType_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string payloadType = 7;</code>
         *
         * @return The bytes for payloadType.
         */
        public com.google.protobuf.ByteString
        getPayloadTypeBytes()
        {
            java.lang.Object ref = payloadType_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                payloadType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string payloadType = 7;</code>
         *
         * @param value The payloadType to set.
         * @return This builder for chaining.
         */
        public Builder setPayloadType(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            payloadType_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>string payloadType = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPayloadType() {
            payloadType_ = getDefaultInstance().getPayloadType();
            bitField0_ = (bitField0_ & ~ 0x00000040);
            onChanged();
            return this;
        }

        /**
         * <code>string payloadType = 7;</code>
         *
         * @param value The bytes for payloadType to set.
         * @return This builder for chaining.
         */
        public Builder setPayloadTypeBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            payloadType_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes payload = 8;</code>
         *
         * @return The payload.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        /**
         * <code>bytes payload = 8;</code>
         *
         * @param value The payload to set.
         * @return This builder for chaining.
         */
        public Builder setPayload(com.google.protobuf.ByteString value) {
            if(value == null) {
                throw new NullPointerException();
            }
            payload_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        /**
         * <code>bytes payload = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPayload() {
            bitField0_ = (bitField0_ & ~ 0x00000080);
            payload_ = getDefaultInstance().getPayload();
            onChanged();
            return this;
        }

        private java.lang.Object lodIdNew_ = "";

        /**
         * <code>string lodIdNew = 9;</code>
         *
         * @return The lodIdNew.
         */
        public java.lang.String getLodIdNew() {
            java.lang.Object ref = lodIdNew_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                lodIdNew_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string lodIdNew = 9;</code>
         *
         * @return The bytes for lodIdNew.
         */
        public com.google.protobuf.ByteString
        getLodIdNewBytes()
        {
            java.lang.Object ref = lodIdNew_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                lodIdNew_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string lodIdNew = 9;</code>
         *
         * @param value The lodIdNew to set.
         * @return This builder for chaining.
         */
        public Builder setLodIdNew(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            lodIdNew_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        /**
         * <code>string lodIdNew = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLodIdNew() {
            lodIdNew_ = getDefaultInstance().getLodIdNew();
            bitField0_ = (bitField0_ & ~ 0x00000100);
            onChanged();
            return this;
        }

        /**
         * <code>string lodIdNew = 9;</code>
         *
         * @param value The bytes for lodIdNew to set.
         * @return This builder for chaining.
         */
        public Builder setLodIdNewBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            lodIdNew_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        private java.lang.Object serverTiming_ = "";

        /**
         * <code>string serverTiming = 10;</code>
         *
         * @return The serverTiming.
         */
        public java.lang.String getServerTiming() {
            java.lang.Object ref = serverTiming_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                serverTiming_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string serverTiming = 10;</code>
         *
         * @return The bytes for serverTiming.
         */
        public com.google.protobuf.ByteString
        getServerTimingBytes()
        {
            java.lang.Object ref = serverTiming_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                serverTiming_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string serverTiming = 10;</code>
         *
         * @param value The serverTiming to set.
         * @return This builder for chaining.
         */
        public Builder setServerTiming(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            serverTiming_ = value;
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>string serverTiming = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearServerTiming() {
            serverTiming_ = getDefaultInstance().getServerTiming();
            bitField0_ = (bitField0_ & ~ 0x00000200);
            onChanged();
            return this;
        }

        /**
         * <code>string serverTiming = 10;</code>
         *
         * @param value The bytes for serverTiming to set.
         * @return This builder for chaining.
         */
        public Builder setServerTimingBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            serverTiming_ = value;
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        private java.lang.Object msgID_ = "";

        /**
         * <code>string msgID = 11;</code>
         *
         * @return The msgID.
         */
        public java.lang.String getMsgID() {
            java.lang.Object ref = msgID_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msgID_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string msgID = 11;</code>
         *
         * @return The bytes for msgID.
         */
        public com.google.protobuf.ByteString
        getMsgIDBytes()
        {
            java.lang.Object ref = msgID_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msgID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string msgID = 11;</code>
         *
         * @param value The msgID to set.
         * @return This builder for chaining.
         */
        public Builder setMsgID(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            msgID_ = value;
            bitField0_ |= 0x00000400;
            onChanged();
            return this;
        }

        /**
         * <code>string msgID = 11;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgID() {
            msgID_ = getDefaultInstance().getMsgID();
            bitField0_ = (bitField0_ & ~ 0x00000400);
            onChanged();
            return this;
        }

        /**
         * <code>string msgID = 11;</code>
         *
         * @param value The bytes for msgID to set.
         * @return This builder for chaining.
         */
        public Builder setMsgIDBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            msgID_ = value;
            bitField0_ |= 0x00000400;
            onChanged();
            return this;
        }

        private int frameType_;

        /**
         * <code>int32 frameType = 12;</code>
         *
         * @return The frameType.
         */
        @java.lang.Override
        public int getFrameType() {
            return frameType_;
        }

        /**
         * <code>int32 frameType = 12;</code>
         *
         * @param value The frameType to set.
         * @return This builder for chaining.
         */
        public Builder setFrameType(int value) {

            frameType_ = value;
            bitField0_ |= 0x00000800;
            onChanged();
            return this;
        }

        /**
         * <code>int32 frameType = 12;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearFrameType() {
            bitField0_ = (bitField0_ & ~ 0x00000800);
            frameType_ = 0;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:PushFrame)
    }

    // @@protoc_insertion_point(class_scope:PushFrame)
    private static final PushFrame DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new PushFrame();
    }

    public static PushFrame getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushFrame>
            PARSER = new com.google.protobuf.AbstractParser<PushFrame>() {
        @java.lang.Override
        public PushFrame parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch(com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch(java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<PushFrame> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushFrame> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public PushFrame getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

