// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

public interface PushFrameOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PushFrame)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 seqID = 1;</code>
     *
     * @return The seqID.
     */
    long getSeqID();

    /**
     * <code>uint64 logID = 2;</code>
     *
     * @return The logID.
     */
    long getLogID();

    /**
     * <code>int32 service = 3;</code>
     *
     * @return The service.
     */
    int getService();

    /**
     * <code>int32 method = 4;</code>
     *
     * @return The method.
     */
    int getMethod();

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    java.util.List<Header>
    getHeadersList();

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    Header getHeaders(int index);

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    int getHeadersCount();

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    java.util.List<? extends HeaderOrBuilder>
    getHeadersOrBuilderList();

    /**
     * <code>repeated .Header headers = 5;</code>
     */
    HeaderOrBuilder getHeadersOrBuilder(
            int index);

    /**
     * <code>string payloadEncoding = 6;</code>
     *
     * @return The payloadEncoding.
     */
    java.lang.String getPayloadEncoding();

    /**
     * <code>string payloadEncoding = 6;</code>
     *
     * @return The bytes for payloadEncoding.
     */
    com.google.protobuf.ByteString
    getPayloadEncodingBytes();

    /**
     * <code>string payloadType = 7;</code>
     *
     * @return The payloadType.
     */
    java.lang.String getPayloadType();

    /**
     * <code>string payloadType = 7;</code>
     *
     * @return The bytes for payloadType.
     */
    com.google.protobuf.ByteString
    getPayloadTypeBytes();

    /**
     * <code>bytes payload = 8;</code>
     *
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>string lodIdNew = 9;</code>
     *
     * @return The lodIdNew.
     */
    java.lang.String getLodIdNew();

    /**
     * <code>string lodIdNew = 9;</code>
     *
     * @return The bytes for lodIdNew.
     */
    com.google.protobuf.ByteString
    getLodIdNewBytes();

    /**
     * <code>string serverTiming = 10;</code>
     *
     * @return The serverTiming.
     */
    java.lang.String getServerTiming();

    /**
     * <code>string serverTiming = 10;</code>
     *
     * @return The bytes for serverTiming.
     */
    com.google.protobuf.ByteString
    getServerTimingBytes();

    /**
     * <code>string msgID = 11;</code>
     *
     * @return The msgID.
     */
    java.lang.String getMsgID();

    /**
     * <code>string msgID = 11;</code>
     *
     * @return The bytes for msgID.
     */
    com.google.protobuf.ByteString
    getMsgIDBytes();

    /**
     * <code>int32 frameType = 12;</code>
     *
     * @return The frameType.
     */
    int getFrameType();
}
