// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

/**
 * Protobuf type {@code ResponseBody}
 */
public final class ResponseBody extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ResponseBody)
        ResponseBodyOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                ResponseBody.class.getName());
    }

    // Use ResponseBody.newBuilder() to construct.
    private ResponseBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ResponseBody() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor()
    {
        return ChatMessage.internal_static_ResponseBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable()
    {
        return ChatMessage.internal_static_ResponseBody_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ResponseBody.class, ResponseBody.Builder.class);
    }

    private int bitField0_;
    public static final int HASNEWMESSAGENOTIFY_FIELD_NUMBER = 500;
    private NewMessageNotify hasNewMessageNotify_;

    /**
     * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
     *
     * @return Whether the hasNewMessageNotify field is set.
     */
    @java.lang.Override
    public boolean hasHasNewMessageNotify() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
     *
     * @return The hasNewMessageNotify.
     */
    @java.lang.Override
    public NewMessageNotify getHasNewMessageNotify() {
        return hasNewMessageNotify_ == null ? NewMessageNotify.getDefaultInstance() : hasNewMessageNotify_;
    }

    /**
     * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
     */
    @java.lang.Override
    public NewMessageNotifyOrBuilder getHasNewMessageNotifyOrBuilder() {
        return hasNewMessageNotify_ == null ? NewMessageNotify.getDefaultInstance() : hasNewMessageNotify_;
    }

    private byte memoizedIsInitialized = - 1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if(isInitialized == 1) return true;
        if(isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException
    {
        if(((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(500, getHasNewMessageNotify());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if(size != - 1) return size;

        size = 0;
        if(((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(500, getHasNewMessageNotify());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if(obj == this) {
            return true;
        }
        if(! (obj instanceof ResponseBody)) {
            return super.equals(obj);
        }
        ResponseBody other = (ResponseBody) obj;

        if(hasHasNewMessageNotify() != other.hasHasNewMessageNotify()) return false;
        if(hasHasNewMessageNotify()) {
            if(! getHasNewMessageNotify()
                    .equals(other.getHasNewMessageNotify())) return false;
        }
        if(! getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if(memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if(hasHasNewMessageNotify()) {
            hash = (37 * hash) + HASNEWMESSAGENOTIFY_FIELD_NUMBER;
            hash = (53 * hash) + getHasNewMessageNotify().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static ResponseBody parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static ResponseBody parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ResponseBody parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static ResponseBody parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ResponseBody parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static ResponseBody parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ResponseBody parseFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static ResponseBody parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ResponseBody parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static ResponseBody parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ResponseBody parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static ResponseBody parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ResponseBody prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent)
    {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code ResponseBody}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ResponseBody)
            ResponseBodyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatMessage.internal_static_ResponseBody_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatMessage.internal_static_ResponseBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ResponseBody.class, ResponseBody.Builder.class);
        }

        // Construct using ResponseBody.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent)
        {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if(com.google.protobuf.GeneratedMessage
                    .alwaysUseFieldBuilders) {
                getHasNewMessageNotifyFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            hasNewMessageNotify_ = null;
            if(hasNewMessageNotifyBuilder_ != null) {
                hasNewMessageNotifyBuilder_.dispose();
                hasNewMessageNotifyBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType()
        {
            return ChatMessage.internal_static_ResponseBody_descriptor;
        }

        @java.lang.Override
        public ResponseBody getDefaultInstanceForType() {
            return ResponseBody.getDefaultInstance();
        }

        @java.lang.Override
        public ResponseBody build() {
            ResponseBody result = buildPartial();
            if(! result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public ResponseBody buildPartial() {
            ResponseBody result = new ResponseBody(this);
            if(bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(ResponseBody result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if(((from_bitField0_ & 0x00000001) != 0)) {
                result.hasNewMessageNotify_ = hasNewMessageNotifyBuilder_ == null
                        ? hasNewMessageNotify_
                        : hasNewMessageNotifyBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if(other instanceof ResponseBody) {
                return mergeFrom((ResponseBody) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(ResponseBody other) {
            if(other == ResponseBody.getDefaultInstance()) return this;
            if(other.hasHasNewMessageNotify()) {
                mergeHasNewMessageNotify(other.getHasNewMessageNotify());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            if(extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while(! done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 4002: {
                            input.readMessage(
                                    getHasNewMessageNotifyFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 4002
                        default: {
                            if(! super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private NewMessageNotify hasNewMessageNotify_;
        private com.google.protobuf.SingleFieldBuilder<
                NewMessageNotify, NewMessageNotify.Builder, NewMessageNotifyOrBuilder> hasNewMessageNotifyBuilder_;

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         *
         * @return Whether the hasNewMessageNotify field is set.
         */
        public boolean hasHasNewMessageNotify() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         *
         * @return The hasNewMessageNotify.
         */
        public NewMessageNotify getHasNewMessageNotify() {
            if(hasNewMessageNotifyBuilder_ == null) {
                return hasNewMessageNotify_ == null ? NewMessageNotify.getDefaultInstance() : hasNewMessageNotify_;
            } else {
                return hasNewMessageNotifyBuilder_.getMessage();
            }
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        public Builder setHasNewMessageNotify(NewMessageNotify value) {
            if(hasNewMessageNotifyBuilder_ == null) {
                if(value == null) {
                    throw new NullPointerException();
                }
                hasNewMessageNotify_ = value;
            } else {
                hasNewMessageNotifyBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        public Builder setHasNewMessageNotify(
                NewMessageNotify.Builder builderForValue)
        {
            if(hasNewMessageNotifyBuilder_ == null) {
                hasNewMessageNotify_ = builderForValue.build();
            } else {
                hasNewMessageNotifyBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        public Builder mergeHasNewMessageNotify(NewMessageNotify value) {
            if(hasNewMessageNotifyBuilder_ == null) {
                if(((bitField0_ & 0x00000001) != 0) &&
                        hasNewMessageNotify_ != null &&
                        hasNewMessageNotify_ != NewMessageNotify.getDefaultInstance()) {
                    getHasNewMessageNotifyBuilder().mergeFrom(value);
                } else {
                    hasNewMessageNotify_ = value;
                }
            } else {
                hasNewMessageNotifyBuilder_.mergeFrom(value);
            }
            if(hasNewMessageNotify_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        public Builder clearHasNewMessageNotify() {
            bitField0_ = (bitField0_ & ~ 0x00000001);
            hasNewMessageNotify_ = null;
            if(hasNewMessageNotifyBuilder_ != null) {
                hasNewMessageNotifyBuilder_.dispose();
                hasNewMessageNotifyBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        public NewMessageNotify.Builder getHasNewMessageNotifyBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getHasNewMessageNotifyFieldBuilder().getBuilder();
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        public NewMessageNotifyOrBuilder getHasNewMessageNotifyOrBuilder() {
            if(hasNewMessageNotifyBuilder_ != null) {
                return hasNewMessageNotifyBuilder_.getMessageOrBuilder();
            } else {
                return hasNewMessageNotify_ == null ?
                        NewMessageNotify.getDefaultInstance() : hasNewMessageNotify_;
            }
        }

        /**
         * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
                NewMessageNotify, NewMessageNotify.Builder, NewMessageNotifyOrBuilder>
        getHasNewMessageNotifyFieldBuilder()
        {
            if(hasNewMessageNotifyBuilder_ == null) {
                hasNewMessageNotifyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                        NewMessageNotify, NewMessageNotify.Builder, NewMessageNotifyOrBuilder>(
                        getHasNewMessageNotify(),
                        getParentForChildren(),
                        isClean());
                hasNewMessageNotify_ = null;
            }
            return hasNewMessageNotifyBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:ResponseBody)
    }

    // @@protoc_insertion_point(class_scope:ResponseBody)
    private static final ResponseBody DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new ResponseBody();
    }

    public static ResponseBody getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseBody>
            PARSER = new com.google.protobuf.AbstractParser<ResponseBody>() {
        @java.lang.Override
        public ResponseBody parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch(com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch(java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ResponseBody> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseBody> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public ResponseBody getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

