// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

/**
 * Protobuf type {@code Response}
 */
public final class Response extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Response)
        ResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                Response.class.getName());
    }

    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private Response() {
        errorDesc_ = "";
        logId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor()
    {
        return ChatMessage.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable()
    {
        return ChatMessage.internal_static_Response_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Response.class, Response.Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_ = 0;

    /**
     * <code>int32 cmd = 1;</code>
     *
     * @return The cmd.
     */
    @java.lang.Override
    public int getCmd() {
        return cmd_;
    }

    public static final int SEQUENCEID_FIELD_NUMBER = 2;
    private long sequenceId_ = 0L;

    /**
     * <code>int64 sequenceId = 2;</code>
     *
     * @return The sequenceId.
     */
    @java.lang.Override
    public long getSequenceId() {
        return sequenceId_;
    }

    public static final int STATUSCODE_FIELD_NUMBER = 3;
    private int statusCode_ = 0;

    /**
     * <code>int32 statusCode = 3;</code>
     *
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
        return statusCode_;
    }

    public static final int ERRORDESC_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errorDesc_ = "";

    /**
     * <code>string errorDesc = 4;</code>
     *
     * @return The errorDesc.
     */
    @java.lang.Override
    public java.lang.String getErrorDesc() {
        java.lang.Object ref = errorDesc_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            errorDesc_ = s;
            return s;
        }
    }

    /**
     * <code>string errorDesc = 4;</code>
     *
     * @return The bytes for errorDesc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getErrorDescBytes()
    {
        java.lang.Object ref = errorDesc_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            errorDesc_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int INBOXTYPE_FIELD_NUMBER = 5;
    private int inboxType_ = 0;

    /**
     * <code>int32 inboxType = 5;</code>
     *
     * @return The inboxType.
     */
    @java.lang.Override
    public int getInboxType() {
        return inboxType_;
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private ResponseBody body_;

    /**
     * <code>.ResponseBody body = 6;</code>
     *
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.ResponseBody body = 6;</code>
     *
     * @return The body.
     */
    @java.lang.Override
    public ResponseBody getBody() {
        return body_ == null ? ResponseBody.getDefaultInstance() : body_;
    }

    /**
     * <code>.ResponseBody body = 6;</code>
     */
    @java.lang.Override
    public ResponseBodyOrBuilder getBodyOrBuilder() {
        return body_ == null ? ResponseBody.getDefaultInstance() : body_;
    }

    public static final int LOGID_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object logId_ = "";

    /**
     * <code>string logId = 7;</code>
     *
     * @return The logId.
     */
    @java.lang.Override
    public java.lang.String getLogId() {
        java.lang.Object ref = logId_;
        if(ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            logId_ = s;
            return s;
        }
    }

    /**
     * <code>string logId = 7;</code>
     *
     * @return The bytes for logId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getLogIdBytes()
    {
        java.lang.Object ref = logId_;
        if(ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            logId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int STARTTIMESTAMP_FIELD_NUMBER = 9;
    private long startTimestamp_ = 0L;

    /**
     * <pre>
     * repeated Entity headers = 8;
     * </pre>
     *
     * <code>int64 startTimestamp = 9;</code>
     *
     * @return The startTimestamp.
     */
    @java.lang.Override
    public long getStartTimestamp() {
        return startTimestamp_;
    }

    public static final int SERVEREXECUTIONENDTIME_FIELD_NUMBER = 10;
    private long serverExecutionEndTime_ = 0L;

    /**
     * <code>int64 serverExecutionEndTime = 10;</code>
     *
     * @return The serverExecutionEndTime.
     */
    @java.lang.Override
    public long getServerExecutionEndTime() {
        return serverExecutionEndTime_;
    }

    private byte memoizedIsInitialized = - 1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if(isInitialized == 1) return true;
        if(isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException
    {
        if(cmd_ != 0) {
            output.writeInt32(1, cmd_);
        }
        if(sequenceId_ != 0L) {
            output.writeInt64(2, sequenceId_);
        }
        if(statusCode_ != 0) {
            output.writeInt32(3, statusCode_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(errorDesc_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 4, errorDesc_);
        }
        if(inboxType_ != 0) {
            output.writeInt32(5, inboxType_);
        }
        if(((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(6, getBody());
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(logId_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 7, logId_);
        }
        if(startTimestamp_ != 0L) {
            output.writeInt64(9, startTimestamp_);
        }
        if(serverExecutionEndTime_ != 0L) {
            output.writeInt64(10, serverExecutionEndTime_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if(size != - 1) return size;

        size = 0;
        if(cmd_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, cmd_);
        }
        if(sequenceId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(2, sequenceId_);
        }
        if(statusCode_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, statusCode_);
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(errorDesc_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(4, errorDesc_);
        }
        if(inboxType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(5, inboxType_);
        }
        if(((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, getBody());
        }
        if(! com.google.protobuf.GeneratedMessage.isStringEmpty(logId_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(7, logId_);
        }
        if(startTimestamp_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(9, startTimestamp_);
        }
        if(serverExecutionEndTime_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(10, serverExecutionEndTime_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if(obj == this) {
            return true;
        }
        if(! (obj instanceof Response)) {
            return super.equals(obj);
        }
        Response other = (Response) obj;

        if(getCmd()
                != other.getCmd()) return false;
        if(getSequenceId()
                != other.getSequenceId()) return false;
        if(getStatusCode()
                != other.getStatusCode()) return false;
        if(! getErrorDesc()
                .equals(other.getErrorDesc())) return false;
        if(getInboxType()
                != other.getInboxType()) return false;
        if(hasBody() != other.hasBody()) return false;
        if(hasBody()) {
            if(! getBody()
                    .equals(other.getBody())) return false;
        }
        if(! getLogId()
                .equals(other.getLogId())) return false;
        if(getStartTimestamp()
                != other.getStartTimestamp()) return false;
        if(getServerExecutionEndTime()
                != other.getServerExecutionEndTime()) return false;
        if(! getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if(memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + getCmd();
        hash = (37 * hash) + SEQUENCEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getSequenceId());
        hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
        hash = (53 * hash) + getStatusCode();
        hash = (37 * hash) + ERRORDESC_FIELD_NUMBER;
        hash = (53 * hash) + getErrorDesc().hashCode();
        hash = (37 * hash) + INBOXTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getInboxType();
        if(hasBody()) {
            hash = (37 * hash) + BODY_FIELD_NUMBER;
            hash = (53 * hash) + getBody().hashCode();
        }
        hash = (37 * hash) + LOGID_FIELD_NUMBER;
        hash = (53 * hash) + getLogId().hashCode();
        hash = (37 * hash) + STARTTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getStartTimestamp());
        hash = (37 * hash) + SERVEREXECUTIONENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getServerExecutionEndTime());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Response parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static Response parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Response parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static Response parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Response parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data);
    }

    public static Response parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException
    {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Response parseFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static Response parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Response parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Response parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Response parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static Response parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException
    {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent)
    {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Response)
            ResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return ChatMessage.internal_static_Response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return ChatMessage.internal_static_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Response.class, Response.Builder.class);
        }

        // Construct using Response.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent)
        {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if(com.google.protobuf.GeneratedMessage
                    .alwaysUseFieldBuilders) {
                getBodyFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            cmd_ = 0;
            sequenceId_ = 0L;
            statusCode_ = 0;
            errorDesc_ = "";
            inboxType_ = 0;
            body_ = null;
            if(bodyBuilder_ != null) {
                bodyBuilder_.dispose();
                bodyBuilder_ = null;
            }
            logId_ = "";
            startTimestamp_ = 0L;
            serverExecutionEndTime_ = 0L;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType()
        {
            return ChatMessage.internal_static_Response_descriptor;
        }

        @java.lang.Override
        public Response getDefaultInstanceForType() {
            return Response.getDefaultInstance();
        }

        @java.lang.Override
        public Response build() {
            Response result = buildPartial();
            if(! result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public Response buildPartial() {
            Response result = new Response(this);
            if(bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(Response result) {
            int from_bitField0_ = bitField0_;
            if(((from_bitField0_ & 0x00000001) != 0)) {
                result.cmd_ = cmd_;
            }
            if(((from_bitField0_ & 0x00000002) != 0)) {
                result.sequenceId_ = sequenceId_;
            }
            if(((from_bitField0_ & 0x00000004) != 0)) {
                result.statusCode_ = statusCode_;
            }
            if(((from_bitField0_ & 0x00000008) != 0)) {
                result.errorDesc_ = errorDesc_;
            }
            if(((from_bitField0_ & 0x00000010) != 0)) {
                result.inboxType_ = inboxType_;
            }
            int to_bitField0_ = 0;
            if(((from_bitField0_ & 0x00000020) != 0)) {
                result.body_ = bodyBuilder_ == null
                        ? body_
                        : bodyBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if(((from_bitField0_ & 0x00000040) != 0)) {
                result.logId_ = logId_;
            }
            if(((from_bitField0_ & 0x00000080) != 0)) {
                result.startTimestamp_ = startTimestamp_;
            }
            if(((from_bitField0_ & 0x00000100) != 0)) {
                result.serverExecutionEndTime_ = serverExecutionEndTime_;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if(other instanceof Response) {
                return mergeFrom((Response) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Response other) {
            if(other == Response.getDefaultInstance()) return this;
            if(other.getCmd() != 0) {
                setCmd(other.getCmd());
            }
            if(other.getSequenceId() != 0L) {
                setSequenceId(other.getSequenceId());
            }
            if(other.getStatusCode() != 0) {
                setStatusCode(other.getStatusCode());
            }
            if(! other.getErrorDesc().isEmpty()) {
                errorDesc_ = other.errorDesc_;
                bitField0_ |= 0x00000008;
                onChanged();
            }
            if(other.getInboxType() != 0) {
                setInboxType(other.getInboxType());
            }
            if(other.hasBody()) {
                mergeBody(other.getBody());
            }
            if(! other.getLogId().isEmpty()) {
                logId_ = other.logId_;
                bitField0_ |= 0x00000040;
                onChanged();
            }
            if(other.getStartTimestamp() != 0L) {
                setStartTimestamp(other.getStartTimestamp());
            }
            if(other.getServerExecutionEndTime() != 0L) {
                setServerExecutionEndTime(other.getServerExecutionEndTime());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            if(extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while(! done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            cmd_ = input.readInt32();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 16: {
                            sequenceId_ = input.readInt64();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        case 24: {
                            statusCode_ = input.readInt32();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 34: {
                            errorDesc_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 34
                        case 40: {
                            inboxType_ = input.readInt32();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 40
                        case 50: {
                            input.readMessage(
                                    getBodyFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 50
                        case 58: {
                            logId_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 58
                        case 72: {
                            startTimestamp_ = input.readInt64();
                            bitField0_ |= 0x00000080;
                            break;
                        } // case 72
                        case 80: {
                            serverExecutionEndTime_ = input.readInt64();
                            bitField0_ |= 0x00000100;
                            break;
                        } // case 80
                        default: {
                            if(! super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private int cmd_;

        /**
         * <code>int32 cmd = 1;</code>
         *
         * @return The cmd.
         */
        @java.lang.Override
        public int getCmd() {
            return cmd_;
        }

        /**
         * <code>int32 cmd = 1;</code>
         *
         * @param value The cmd to set.
         * @return This builder for chaining.
         */
        public Builder setCmd(int value) {

            cmd_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int32 cmd = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCmd() {
            bitField0_ = (bitField0_ & ~ 0x00000001);
            cmd_ = 0;
            onChanged();
            return this;
        }

        private long sequenceId_;

        /**
         * <code>int64 sequenceId = 2;</code>
         *
         * @return The sequenceId.
         */
        @java.lang.Override
        public long getSequenceId() {
            return sequenceId_;
        }

        /**
         * <code>int64 sequenceId = 2;</code>
         *
         * @param value The sequenceId to set.
         * @return This builder for chaining.
         */
        public Builder setSequenceId(long value) {

            sequenceId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>int64 sequenceId = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSequenceId() {
            bitField0_ = (bitField0_ & ~ 0x00000002);
            sequenceId_ = 0L;
            onChanged();
            return this;
        }

        private int statusCode_;

        /**
         * <code>int32 statusCode = 3;</code>
         *
         * @return The statusCode.
         */
        @java.lang.Override
        public int getStatusCode() {
            return statusCode_;
        }

        /**
         * <code>int32 statusCode = 3;</code>
         *
         * @param value The statusCode to set.
         * @return This builder for chaining.
         */
        public Builder setStatusCode(int value) {

            statusCode_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>int32 statusCode = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStatusCode() {
            bitField0_ = (bitField0_ & ~ 0x00000004);
            statusCode_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object errorDesc_ = "";

        /**
         * <code>string errorDesc = 4;</code>
         *
         * @return The errorDesc.
         */
        public java.lang.String getErrorDesc() {
            java.lang.Object ref = errorDesc_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                errorDesc_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string errorDesc = 4;</code>
         *
         * @return The bytes for errorDesc.
         */
        public com.google.protobuf.ByteString
        getErrorDescBytes()
        {
            java.lang.Object ref = errorDesc_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errorDesc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string errorDesc = 4;</code>
         *
         * @param value The errorDesc to set.
         * @return This builder for chaining.
         */
        public Builder setErrorDesc(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            errorDesc_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>string errorDesc = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorDesc() {
            errorDesc_ = getDefaultInstance().getErrorDesc();
            bitField0_ = (bitField0_ & ~ 0x00000008);
            onChanged();
            return this;
        }

        /**
         * <code>string errorDesc = 4;</code>
         *
         * @param value The bytes for errorDesc to set.
         * @return This builder for chaining.
         */
        public Builder setErrorDescBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            errorDesc_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        private int inboxType_;

        /**
         * <code>int32 inboxType = 5;</code>
         *
         * @return The inboxType.
         */
        @java.lang.Override
        public int getInboxType() {
            return inboxType_;
        }

        /**
         * <code>int32 inboxType = 5;</code>
         *
         * @param value The inboxType to set.
         * @return This builder for chaining.
         */
        public Builder setInboxType(int value) {

            inboxType_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>int32 inboxType = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearInboxType() {
            bitField0_ = (bitField0_ & ~ 0x00000010);
            inboxType_ = 0;
            onChanged();
            return this;
        }

        private ResponseBody body_;
        private com.google.protobuf.SingleFieldBuilder<
                ResponseBody, ResponseBody.Builder, ResponseBodyOrBuilder> bodyBuilder_;

        /**
         * <code>.ResponseBody body = 6;</code>
         *
         * @return Whether the body field is set.
         */
        public boolean hasBody() {
            return ((bitField0_ & 0x00000020) != 0);
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         *
         * @return The body.
         */
        public ResponseBody getBody() {
            if(bodyBuilder_ == null) {
                return body_ == null ? ResponseBody.getDefaultInstance() : body_;
            } else {
                return bodyBuilder_.getMessage();
            }
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        public Builder setBody(ResponseBody value) {
            if(bodyBuilder_ == null) {
                if(value == null) {
                    throw new NullPointerException();
                }
                body_ = value;
            } else {
                bodyBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        public Builder setBody(
                ResponseBody.Builder builderForValue)
        {
            if(bodyBuilder_ == null) {
                body_ = builderForValue.build();
            } else {
                bodyBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        public Builder mergeBody(ResponseBody value) {
            if(bodyBuilder_ == null) {
                if(((bitField0_ & 0x00000020) != 0) &&
                        body_ != null &&
                        body_ != ResponseBody.getDefaultInstance()) {
                    getBodyBuilder().mergeFrom(value);
                } else {
                    body_ = value;
                }
            } else {
                bodyBuilder_.mergeFrom(value);
            }
            if(body_ != null) {
                bitField0_ |= 0x00000020;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        public Builder clearBody() {
            bitField0_ = (bitField0_ & ~ 0x00000020);
            body_ = null;
            if(bodyBuilder_ != null) {
                bodyBuilder_.dispose();
                bodyBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        public ResponseBody.Builder getBodyBuilder() {
            bitField0_ |= 0x00000020;
            onChanged();
            return getBodyFieldBuilder().getBuilder();
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        public ResponseBodyOrBuilder getBodyOrBuilder() {
            if(bodyBuilder_ != null) {
                return bodyBuilder_.getMessageOrBuilder();
            } else {
                return body_ == null ?
                        ResponseBody.getDefaultInstance() : body_;
            }
        }

        /**
         * <code>.ResponseBody body = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
                ResponseBody, ResponseBody.Builder, ResponseBodyOrBuilder>
        getBodyFieldBuilder()
        {
            if(bodyBuilder_ == null) {
                bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                        ResponseBody, ResponseBody.Builder, ResponseBodyOrBuilder>(
                        getBody(),
                        getParentForChildren(),
                        isClean());
                body_ = null;
            }
            return bodyBuilder_;
        }

        private java.lang.Object logId_ = "";

        /**
         * <code>string logId = 7;</code>
         *
         * @return The logId.
         */
        public java.lang.String getLogId() {
            java.lang.Object ref = logId_;
            if(! (ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                logId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string logId = 7;</code>
         *
         * @return The bytes for logId.
         */
        public com.google.protobuf.ByteString
        getLogIdBytes()
        {
            java.lang.Object ref = logId_;
            if(ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                logId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string logId = 7;</code>
         *
         * @param value The logId to set.
         * @return This builder for chaining.
         */
        public Builder setLogId(
                java.lang.String value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            logId_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>string logId = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLogId() {
            logId_ = getDefaultInstance().getLogId();
            bitField0_ = (bitField0_ & ~ 0x00000040);
            onChanged();
            return this;
        }

        /**
         * <code>string logId = 7;</code>
         *
         * @param value The bytes for logId to set.
         * @return This builder for chaining.
         */
        public Builder setLogIdBytes(
                com.google.protobuf.ByteString value)
        {
            if(value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            logId_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        private long startTimestamp_;

        /**
         * <pre>
         * repeated Entity headers = 8;
         * </pre>
         *
         * <code>int64 startTimestamp = 9;</code>
         *
         * @return The startTimestamp.
         */
        @java.lang.Override
        public long getStartTimestamp() {
            return startTimestamp_;
        }

        /**
         * <pre>
         * repeated Entity headers = 8;
         * </pre>
         *
         * <code>int64 startTimestamp = 9;</code>
         *
         * @param value The startTimestamp to set.
         * @return This builder for chaining.
         */
        public Builder setStartTimestamp(long value) {

            startTimestamp_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * repeated Entity headers = 8;
         * </pre>
         *
         * <code>int64 startTimestamp = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStartTimestamp() {
            bitField0_ = (bitField0_ & ~ 0x00000080);
            startTimestamp_ = 0L;
            onChanged();
            return this;
        }

        private long serverExecutionEndTime_;

        /**
         * <code>int64 serverExecutionEndTime = 10;</code>
         *
         * @return The serverExecutionEndTime.
         */
        @java.lang.Override
        public long getServerExecutionEndTime() {
            return serverExecutionEndTime_;
        }

        /**
         * <code>int64 serverExecutionEndTime = 10;</code>
         *
         * @param value The serverExecutionEndTime to set.
         * @return This builder for chaining.
         */
        public Builder setServerExecutionEndTime(long value) {

            serverExecutionEndTime_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        /**
         * <code>int64 serverExecutionEndTime = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearServerExecutionEndTime() {
            bitField0_ = (bitField0_ & ~ 0x00000100);
            serverExecutionEndTime_ = 0L;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final Response DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Response();
    }

    public static Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
            PARSER = new com.google.protobuf.AbstractParser<Response>() {
        @java.lang.Override
        public Response parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch(com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch(com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch(java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

