// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Response)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd = 1;</code>
     *
     * @return The cmd.
     */
    int getCmd();

    /**
     * <code>int64 sequenceId = 2;</code>
     *
     * @return The sequenceId.
     */
    long getSequenceId();

    /**
     * <code>int32 statusCode = 3;</code>
     *
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <code>string errorDesc = 4;</code>
     *
     * @return The errorDesc.
     */
    String getErrorDesc();

    /**
     * <code>string errorDesc = 4;</code>
     *
     * @return The bytes for errorDesc.
     */
    com.google.protobuf.ByteString
    getErrorDescBytes();

    /**
     * <code>int32 inboxType = 5;</code>
     *
     * @return The inboxType.
     */
    int getInboxType();

    /**
     * <code>.ResponseBody body = 6;</code>
     *
     * @return Whether the body field is set.
     */
    boolean hasBody();

    /**
     * <code>.ResponseBody body = 6;</code>
     *
     * @return The body.
     */
    ResponseBody getBody();

    /**
     * <code>.ResponseBody body = 6;</code>
     */
    ResponseBodyOrBuilder getBodyOrBuilder();

    /**
     * <code>string logId = 7;</code>
     *
     * @return The logId.
     */
    String getLogId();

    /**
     * <code>string logId = 7;</code>
     *
     * @return The bytes for logId.
     */
    com.google.protobuf.ByteString
    getLogIdBytes();

    /**
     * <pre>
     * repeated Entity headers = 8;
     * </pre>
     *
     * <code>int64 startTimestamp = 9;</code>
     *
     * @return The startTimestamp.
     */
    long getStartTimestamp();

    /**
     * <code>int64 serverExecutionEndTime = 10;</code>
     *
     * @return The serverExecutionEndTime.
     */
    long getServerExecutionEndTime();
}
