// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chatMessage.proto
// Protobuf Java Version: 4.29.3
package com.dy_web_api.sdk.message.protobuf;

public interface ResponseBodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ResponseBody)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
     *
     * @return Whether the hasNewMessageNotify field is set.
     */
    boolean hasHasNewMessageNotify();

    /**
     * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
     *
     * @return The hasNewMessageNotify.
     */
    NewMessageNotify getHasNewMessageNotify();

    /**
     * <code>.NewMessageNotify hasNewMessageNotify = 500;</code>
     */
    NewMessageNotifyOrBuilder getHasNewMessageNotifyOrBuilder();
}
